In [3]:
import os
import dotenv
import wandb
import tensorflow as tf
import utils

In [4]:
# --- Dynamic GPU/CPU Selection ---
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print(f"GPUs detected: {[gpu.name for gpu in gpus]}")
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except Exception as e:
        print(f"Could not set memory growth for GPUs: {e}")
else:
    print("No GPUs detected. Using CPU only.")
    os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

# --- W&B Setup ---
dotenv.load_dotenv()
key = os.environ.get("WANDB_API_KEY")

if key:
    print("Logging into Weights & Biases...")
    wandb.login(key=key)
else:
    print("WARNING: WANDB_API_KEY not found in .env. Logging in anonymously.")
    wandb.login()

wandb.init(project="animal-faces-classification")

# --- Training Configuration ---
NUM_EPOCHS = 20
LEARNING_RATE = 0.00001

GPUs detected: ['/physical_device:GPU:0']
WARNING: WANDB_API_KEY not found in .env. Logging in anonymously.

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: pshashid (pshashid-university-of-maryland) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [5]:
if __name__ == "__main__":
    try:
        print("--- Calling Data Preparation Pipeline from utils.py ---")
        train_gen, val_gen = utils.main_prep()

        print("\n--- Training Single ResNet50 Model ---")
        single_resnet = utils.train_model(train_gen, val_gen, architecture="ResNet50", epochs=NUM_EPOCHS, lr=LEARNING_RATE)
        print("\n--- Training Homogeneous Ensemble (ResNet50 x3) ---")
        models_homo, preds_homo, acc_homo = utils.homogeneous_ensemble(train_gen, val_gen, num_models=3, epochs=NUM_EPOCHS, lr=LEARNING_RATE)

        print("\n--- Training Heterogeneous Ensemble (ResNet50 + EfficientNetB0 + MobileNetV2) ---")
        architectures = ["ResNet50", "EfficientNetB0", "MobileNetV2"]
        models_hetero, preds_hetero, acc_hetero = utils.heterogeneous_ensemble(train_gen, val_gen, architectures, epochs=NUM_EPOCHS, lr=LEARNING_RATE)
    except Exception as e:
        print(f"\nAn error occurred during pipeline execution: {e}")
    finally:
        if wandb.run:
            wandb.finish()

--- Calling Data Preparation Pipeline from utils.py ---
--- Starting Data Preparation Pipeline ---
Downloading dataset: andrewmvd/animal-faces...
Using Colab cache for faster access to the 'animal-faces' dataset.
Path to dataset files: /kaggle/input/animal-faces

Collecting image paths and labels (performing Train/Validation Split)...

Train data collected. Samples: 14630

                                          image_path label
0  /kaggle/input/animal-faces/afhq/train/cat/pixa...   cat
1  /kaggle/input/animal-faces/afhq/train/cat/pixa...   cat
2  /kaggle/input/animal-faces/afhq/train/cat/pixa...   cat
3  /kaggle/input/animal-faces/afhq/train/cat/pixa...   cat
4  /kaggle/input/animal-faces/afhq/train/cat/flic...   cat

Validation data collected. Samples: 1500

                                          image_path label
0  /kaggle/input/animal-faces/afhq/val/cat/pixaba...   cat
1  /kaggle/input/animal-faces/afhq/val/cat/flickr...   cat
2  /kaggle/input/animal-faces/afhq/val/cat/flickr...   cat
3  /kaggle/input/animal-faces/afhq/val/cat/pixaba...   cat
4  /kaggle/input/animal-faces/afhq/val/cat/pixaba...   cat

Setting up ImageDataGenerators (including Data Augmentation)...
Found 14630 validated image filenames belonging to 3 classes.
Found 1500 validated image filenames belonging to 3 classes.
Data Augmentation applied. Generators created successfully.

--- Verification of Data Generators ---

[A] Location of Source Images (first 2 paths from train_df):
  - /kaggle/input/animal-faces/afhq/train/cat/pixabay_cat_000354.jpg
  - /kaggle/input/animal-faces/afhq/train/cat/pixabay_cat_002763.jpg
Total Source Images on Disk: 16130

[B] Generated Samples (Source Count) per Generator:
  - Training Samples (train_generator.samples): 14630
  - Validation Samples (val_generator.samples): 1500
  - Batch Size: 256

[B] Batches per Epoch (The number of times augmentation runs per epoch):
  - Training Steps per Epoch: 58
  - Validation Steps per Epoch: 6
--- Verification Complete ---

 Data Preparation Complete. Generators are ready for Transfer Learning.

--- Training Single ResNet50 Model ---

--- Training ResNet50 model ---
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5
94765736/94765736 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

Epoch 1/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 214s 3s/step - accuracy: 0.6377 - loss: 0.8130 - val_accuracy: 0.3440 - val_loss: 1.1210
Epoch 2/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.8584 - loss: 0.3852 - val_accuracy: 0.4627 - val_loss: 1.1070
Epoch 3/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.8894 - loss: 0.2951 - val_accuracy: 0.3527 - val_loss: 1.1119
Epoch 4/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9048 - loss: 0.2520 - val_accuracy: 0.3847 - val_loss: 1.1195
Epoch 5/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9174 - loss: 0.2231 - val_accuracy: 0.5500 - val_loss: 1.0997
Epoch 6/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9183 - loss: 0.2110 - val_accuracy: 0.6260 - val_loss: 0.9653
Epoch 7/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9285 - loss: 0.1926 - val_accuracy: 0.7813 - val_loss: 0.5729
Epoch 8/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9316 - loss: 0.1859 - val_accuracy: 0.8620 - val_loss: 0.3429
Epoch 9/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9366 - loss: 0.1699 - val_accuracy: 0.9287 - val_loss: 0.2077
Epoch 10/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9387 - loss: 0.1654 - val_accuracy: 0.9347 - val_loss: 0.1842
Epoch 11/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9428 - loss: 0.1575 - val_accuracy: 0.9313 - val_loss: 0.1947
Epoch 12/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9416 - loss: 0.1586 - val_accuracy: 0.9327 - val_loss: 0.1796
Epoch 13/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9465 - loss: 0.1434 - val_accuracy: 0.9160 - val_loss: 0.2234
Epoch 14/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9468 - loss: 0.1409 - val_accuracy: 0.9227 - val_loss: 0.1996
Epoch 15/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9529 - loss: 0.1307 - val_accuracy: 0.9353 - val_loss: 0.1742
Epoch 16/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9459 - loss: 0.1408 - val_accuracy: 0.9180 - val_loss: 0.2217
Epoch 17/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9544 - loss: 0.1274 - val_accuracy: 0.9307 - val_loss: 0.1862
Epoch 18/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9548 - loss: 0.1223 - val_accuracy: 0.9260 - val_loss: 0.1885
Epoch 19/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9575 - loss: 0.1162 - val_accuracy: 0.9373 - val_loss: 0.1743
Epoch 20/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9574 - loss: 0.1193 - val_accuracy: 0.9427 - val_loss: 0.1578
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 589ms/step - accuracy: 0.9531 - loss: 0.1247
ResNet50 Validation Accuracy: 0.9427

--- Training Homogeneous Ensemble (ResNet50 x3) ---

--- Training homogeneous model 1/3 (ResNet50_Homo_1) ---

--- Training ResNet50 model ---

Epoch 1/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 124s 2s/step - accuracy: 0.7133 - loss: 0.6824 - val_accuracy: 0.3393 - val_loss: 1.0934
Epoch 2/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.8957 - loss: 0.2744 - val_accuracy: 0.4860 - val_loss: 1.0733
Epoch 3/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9213 - loss: 0.2136 - val_accuracy: 0.6073 - val_loss: 0.9862
Epoch 4/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9263 - loss: 0.1930 - val_accuracy: 0.8033 - val_loss: 0.6648
Epoch 5/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9326 - loss: 0.1800 - val_accuracy: 0.8893 - val_loss: 0.3252
Epoch 6/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9425 - loss: 0.1533 - val_accuracy: 0.9207 - val_loss: 0.2107
Epoch 7/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9401 - loss: 0.1551 - val_accuracy: 0.9167 - val_loss: 0.2108
Epoch 8/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9490 - loss: 0.1356 - val_accuracy: 0.8800 - val_loss: 0.2896
Epoch 9/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9465 - loss: 0.1441 - val_accuracy: 0.9413 - val_loss: 0.1581
Epoch 10/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9494 - loss: 0.1322 - val_accuracy: 0.9040 - val_loss: 0.2567
Epoch 11/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9512 - loss: 0.1304 - val_accuracy: 0.9127 - val_loss: 0.2230
Epoch 12/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9577 - loss: 0.1180 - val_accuracy: 0.9193 - val_loss: 0.2100
Epoch 13/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9576 - loss: 0.1158 - val_accuracy: 0.9247 - val_loss: 0.2014
Epoch 14/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9560 - loss: 0.1168 - val_accuracy: 0.9120 - val_loss: 0.2346
Epoch 15/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9543 - loss: 0.1158 - val_accuracy: 0.9047 - val_loss: 0.2721
Epoch 16/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9586 - loss: 0.1072 - val_accuracy: 0.9493 - val_loss: 0.1332
Epoch 17/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9592 - loss: 0.1094 - val_accuracy: 0.9167 - val_loss: 0.2412
Epoch 18/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9634 - loss: 0.0982 - val_accuracy: 0.9087 - val_loss: 0.2636
Epoch 19/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9656 - loss: 0.0943 - val_accuracy: 0.9467 - val_loss: 0.1430
Epoch 20/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9612 - loss: 0.1010 - val_accuracy: 0.9440 - val_loss: 0.1471
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 599ms/step - accuracy: 0.9541 - loss: 0.1130
ResNet50_Homo_1 Validation Accuracy: 0.9440

--- Training homogeneous model 2/3 (ResNet50_Homo_2) ---

--- Training ResNet50 model ---

Epoch 1/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 120s 2s/step - accuracy: 0.6980 - loss: 0.6956 - val_accuracy: 0.3333 - val_loss: 1.2327
Epoch 2/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9022 - loss: 0.2675 - val_accuracy: 0.3353 - val_loss: 1.1120
Epoch 3/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9224 - loss: 0.2105 - val_accuracy: 0.5847 - val_loss: 0.9595
Epoch 4/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9291 - loss: 0.1989 - val_accuracy: 0.7167 - val_loss: 0.6573
Epoch 5/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9265 - loss: 0.1894 - val_accuracy: 0.8660 - val_loss: 0.3512
Epoch 6/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9404 - loss: 0.1604 - val_accuracy: 0.8567 - val_loss: 0.3523
Epoch 7/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9425 - loss: 0.1535 - val_accuracy: 0.9240 - val_loss: 0.1993
Epoch 8/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9463 - loss: 0.1435 - val_accuracy: 0.9147 - val_loss: 0.2188
Epoch 9/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9485 - loss: 0.1370 - val_accuracy: 0.9420 - val_loss: 0.1572
Epoch 10/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9535 - loss: 0.1258 - val_accuracy: 0.9100 - val_loss: 0.2277
Epoch 11/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9523 - loss: 0.1270 - val_accuracy: 0.9073 - val_loss: 0.2339
Epoch 12/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9551 - loss: 0.1180 - val_accuracy: 0.9493 - val_loss: 0.1537
Epoch 13/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9568 - loss: 0.1174 - val_accuracy: 0.9347 - val_loss: 0.1662
Epoch 14/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9612 - loss: 0.1035 - val_accuracy: 0.9347 - val_loss: 0.1702
Epoch 15/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9615 - loss: 0.1053 - val_accuracy: 0.9200 - val_loss: 0.2247
Epoch 16/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9593 - loss: 0.1116 - val_accuracy: 0.9313 - val_loss: 0.1938
Epoch 17/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9585 - loss: 0.1071 - val_accuracy: 0.9287 - val_loss: 0.1983
Epoch 18/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9638 - loss: 0.0991 - val_accuracy: 0.9393 - val_loss: 0.1597
Epoch 19/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9577 - loss: 0.1124 - val_accuracy: 0.9293 - val_loss: 0.1800
Epoch 20/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9644 - loss: 0.0955 - val_accuracy: 0.8887 - val_loss: 0.3235
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 602ms/step - accuracy: 0.9221 - loss: 0.2259
ResNet50_Homo_2 Validation Accuracy: 0.8887

--- Training homogeneous model 3/3 (ResNet50_Homo_3) ---

--- Training ResNet50 model ---

Epoch 1/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 123s 2s/step - accuracy: 0.7044 - loss: 0.6793 - val_accuracy: 0.3333 - val_loss: 1.1888
Epoch 2/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.8914 - loss: 0.2825 - val_accuracy: 0.4140 - val_loss: 1.1016
Epoch 3/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9204 - loss: 0.2078 - val_accuracy: 0.4347 - val_loss: 1.0241
Epoch 4/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9288 - loss: 0.1929 - val_accuracy: 0.6900 - val_loss: 0.6948
Epoch 5/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 89s 2s/step - accuracy: 0.9307 - loss: 0.1835 - val_accuracy: 0.8687 - val_loss: 0.3338
Epoch 6/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9438 - loss: 0.1524 - val_accuracy: 0.8927 - val_loss: 0.2716
Epoch 7/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9482 - loss: 0.1430 - val_accuracy: 0.8513 - val_loss: 0.3628
Epoch 8/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9459 - loss: 0.1408 - val_accuracy: 0.9373 - val_loss: 0.1696
Epoch 9/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9481 - loss: 0.1400 - val_accuracy: 0.9220 - val_loss: 0.2173
Epoch 10/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9574 - loss: 0.1187 - val_accuracy: 0.8720 - val_loss: 0.3690
Epoch 11/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9563 - loss: 0.1198 - val_accuracy: 0.9233 - val_loss: 0.2032
Epoch 12/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9552 - loss: 0.1177 - val_accuracy: 0.9287 - val_loss: 0.1695
Epoch 13/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 89s 2s/step - accuracy: 0.9576 - loss: 0.1123 - val_accuracy: 0.9047 - val_loss: 0.2376
Epoch 14/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9564 - loss: 0.1174 - val_accuracy: 0.9153 - val_loss: 0.2069
Epoch 15/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9540 - loss: 0.1173 - val_accuracy: 0.9187 - val_loss: 0.2155
Epoch 16/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9586 - loss: 0.1112 - val_accuracy: 0.8693 - val_loss: 0.3683
Epoch 17/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9587 - loss: 0.1114 - val_accuracy: 0.9487 - val_loss: 0.1420
Epoch 18/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9609 - loss: 0.1064 - val_accuracy: 0.9280 - val_loss: 0.1994
Epoch 19/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9641 - loss: 0.0998 - val_accuracy: 0.9353 - val_loss: 0.1728
Epoch 20/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9673 - loss: 0.0929 - val_accuracy: 0.9400 - val_loss: 0.1625
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 616ms/step - accuracy: 0.9532 - loss: 0.1251
ResNet50_Homo_3 Validation Accuracy: 0.9400

--- Evaluating Homogeneous_Ensemble Ensemble ---
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7d10b4439260> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step
Homogeneous_Ensemble Validation Accuracy: 0.9413

--- Training Heterogeneous Ensemble (ResNet50 + EfficientNetB0 + MobileNetV2) ---

--- Training ResNet50 model ---

Epoch 1/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 120s 2s/step - accuracy: 0.7065 - loss: 0.6894 - val_accuracy: 0.3333 - val_loss: 1.1746
Epoch 2/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.8980 - loss: 0.2765 - val_accuracy: 0.3347 - val_loss: 1.1349
Epoch 3/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 89s 2s/step - accuracy: 0.9205 - loss: 0.2147 - val_accuracy: 0.5413 - val_loss: 0.9964
Epoch 4/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9310 - loss: 0.1888 - val_accuracy: 0.8080 - val_loss: 0.6542
Epoch 5/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 90s 2s/step - accuracy: 0.9364 - loss: 0.1680 - val_accuracy: 0.8747 - val_loss: 0.3538
Epoch 6/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 89s 2s/step - accuracy: 0.9400 - loss: 0.1596 - val_accuracy: 0.8580 - val_loss: 0.3389
Epoch 7/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9382 - loss: 0.1623 - val_accuracy: 0.9267 - val_loss: 0.1934
Epoch 8/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9456 - loss: 0.1502 - val_accuracy: 0.9193 - val_loss: 0.2022
Epoch 9/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - accuracy: 0.9505 - loss: 0.1398 - val_accuracy: 0.8740 - val_loss: 0.3668
Epoch 10/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 89s 2s/step - accuracy: 0.9521 - loss: 0.1310 - val_accuracy: 0.9173 - val_loss: 0.2296
Epoch 11/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9505 - loss: 0.1280 - val_accuracy: 0.9180 - val_loss: 0.2440
Epoch 12/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9544 - loss: 0.1220 - val_accuracy: 0.8907 - val_loss: 0.2967
Epoch 13/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9542 - loss: 0.1228 - val_accuracy: 0.8827 - val_loss: 0.3081
Epoch 14/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 89s 2s/step - accuracy: 0.9585 - loss: 0.1104 - val_accuracy: 0.9280 - val_loss: 0.1796
Epoch 15/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9562 - loss: 0.1151 - val_accuracy: 0.9413 - val_loss: 0.1734
Epoch 16/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9555 - loss: 0.1174 - val_accuracy: 0.8880 - val_loss: 0.3055
Epoch 17/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step - accuracy: 0.9594 - loss: 0.1110 - val_accuracy: 0.9327 - val_loss: 0.1683
Epoch 18/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9579 - loss: 0.1067 - val_accuracy: 0.9513 - val_loss: 0.1507
Epoch 19/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9590 - loss: 0.1119 - val_accuracy: 0.9260 - val_loss: 0.1841
Epoch 20/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9635 - loss: 0.0952 - val_accuracy: 0.9333 - val_loss: 0.1777
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 624ms/step - accuracy: 0.9414 - loss: 0.1488
ResNet50_Hetero Validation Accuracy: 0.9333

--- Training EfficientNetB0 model ---
Downloading data from https://storage.googleapis.com/keras-applications/efficientnetb0_notop.h5
16705208/16705208 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step

Epoch 1/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 174s 2s/step - accuracy: 0.3566 - loss: 1.1124 - val_accuracy: 0.3333 - val_loss: 1.1154
Epoch 2/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 84s 1s/step - accuracy: 0.4078 - loss: 1.0805 - val_accuracy: 0.3333 - val_loss: 1.1270
Epoch 3/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.4324 - loss: 1.0649 - val_accuracy: 0.3333 - val_loss: 1.1708
Epoch 4/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.4347 - loss: 1.0510 - val_accuracy: 0.3333 - val_loss: 1.2165
Epoch 5/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.4483 - loss: 1.0404 - val_accuracy: 0.3333 - val_loss: 1.2689
Epoch 6/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.4728 - loss: 1.0297 - val_accuracy: 0.3333 - val_loss: 1.3725
Epoch 7/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.4760 - loss: 1.0129 - val_accuracy: 0.3340 - val_loss: 1.4324
Epoch 8/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.5009 - loss: 0.9865 - val_accuracy: 0.3347 - val_loss: 1.4645
Epoch 9/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.5136 - loss: 0.9711 - val_accuracy: 0.3367 - val_loss: 1.4478
Epoch 10/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.5256 - loss: 0.9525 - val_accuracy: 0.3367 - val_loss: 1.4978
Epoch 11/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.5320 - loss: 0.9325 - val_accuracy: 0.3367 - val_loss: 1.5083
Epoch 12/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.5465 - loss: 0.9161 - val_accuracy: 0.3387 - val_loss: 1.4383
Epoch 13/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.5489 - loss: 0.9054 - val_accuracy: 0.3360 - val_loss: 1.7000
Epoch 14/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 90s 2s/step - accuracy: 0.5626 - loss: 0.8907 - val_accuracy: 0.3373 - val_loss: 1.6660
Epoch 15/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.5661 - loss: 0.8827 - val_accuracy: 0.3380 - val_loss: 1.5228
Epoch 16/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.5781 - loss: 0.8685 - val_accuracy: 0.3373 - val_loss: 1.7254
Epoch 17/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.5823 - loss: 0.8595 - val_accuracy: 0.3360 - val_loss: 1.9616
Epoch 18/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.5731 - loss: 0.8649 - val_accuracy: 0.3360 - val_loss: 1.9604
Epoch 19/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.6067 - loss: 0.8392 - val_accuracy: 0.3373 - val_loss: 1.8378
Epoch 20/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.6056 - loss: 0.8280 - val_accuracy: 0.3360 - val_loss: 2.0982
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 573ms/step - accuracy: 0.2749 - loss: 1.9118
EfficientNetB0_Hetero Validation Accuracy: 0.3360

--- Training MobileNetV2 model ---
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_128_no_top.h5
9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step

Epoch 1/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 139s 2s/step - accuracy: 0.5773 - loss: 0.9262 - val_accuracy: 0.9280 - val_loss: 0.3271
Epoch 2/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 84s 1s/step - accuracy: 0.9382 - loss: 0.2394 - val_accuracy: 0.9667 - val_loss: 0.1554
Epoch 3/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.9691 - loss: 0.1301 - val_accuracy: 0.9753 - val_loss: 0.1034
Epoch 4/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.9821 - loss: 0.0832 - val_accuracy: 0.9780 - val_loss: 0.0766
Epoch 5/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.9846 - loss: 0.0628 - val_accuracy: 0.9813 - val_loss: 0.0637
Epoch 6/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.9871 - loss: 0.0524 - val_accuracy: 0.9833 - val_loss: 0.0514
Epoch 7/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9897 - loss: 0.0394 - val_accuracy: 0.9840 - val_loss: 0.0461
Epoch 8/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.9912 - loss: 0.0344 - val_accuracy: 0.9880 - val_loss: 0.0387
Epoch 9/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9905 - loss: 0.0323 - val_accuracy: 0.9893 - val_loss: 0.0361
Epoch 10/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 84s 1s/step - accuracy: 0.9925 - loss: 0.0282 - val_accuracy: 0.9933 - val_loss: 0.0310
Epoch 11/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9944 - loss: 0.0214 - val_accuracy: 0.9940 - val_loss: 0.0279
Epoch 12/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.9934 - loss: 0.0214 - val_accuracy: 0.9953 - val_loss: 0.0264
Epoch 13/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.9942 - loss: 0.0212 - val_accuracy: 0.9947 - val_loss: 0.0233
Epoch 14/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.9952 - loss: 0.0187 - val_accuracy: 0.9953 - val_loss: 0.0212
Epoch 15/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9951 - loss: 0.0181 - val_accuracy: 0.9947 - val_loss: 0.0201
Epoch 16/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 84s 1s/step - accuracy: 0.9952 - loss: 0.0157 - val_accuracy: 0.9953 - val_loss: 0.0200
Epoch 17/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 2s/step - accuracy: 0.9968 - loss: 0.0144 - val_accuracy: 0.9947 - val_loss: 0.0190
Epoch 18/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9966 - loss: 0.0117 - val_accuracy: 0.9947 - val_loss: 0.0194
Epoch 19/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 86s 1s/step - accuracy: 0.9982 - loss: 0.0089 - val_accuracy: 0.9947 - val_loss: 0.0183
Epoch 20/20
58/58 ━━━━━━━━━━━━━━━━━━━━ 85s 1s/step - accuracy: 0.9977 - loss: 0.0114 - val_accuracy: 0.9947 - val_loss: 0.0182
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 627ms/step - accuracy: 0.9949 - loss: 0.0170
MobileNetV2_Hetero Validation Accuracy: 0.9947

--- Evaluating Heterogeneous_Ensemble Ensemble ---

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7d0e8424ccc0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step
6/6 ━━━━━━━━━━━━━━━━━━━━ 15s 2s/step
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step
Heterogeneous_Ensemble Validation Accuracy: 0.9893

Heterogeneous Ensemble Accuracy: 0.9893