In [ ]:
import os
import dotenv
import wandb
import tensorflow as tf
# import utils_data_io  
# import utils_post_processing 
import utils

In [2]:
# --- Dynamic GPU/CPU Selection ---
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print(f"GPUs detected: {[gpu.name for gpu in gpus]}")
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except Exception as e:
        print(f"Could not set memory growth for GPUs: {e}")
else:
    print("No GPUs detected. Using CPU only.")
    os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

# --- W&B Setup ---
dotenv.load_dotenv()
key = os.environ.get("WANDB_API_KEY")

if key:
    print("Logging into Weights & Biases...")
    wandb.login(key=key)
else:
    print("WARNING: WANDB_API_KEY not found in .env. Logging in anonymously.")
    wandb.login()

wandb.init(project="animal-faces-classification")

# --- Training Configuration ---
NUM_EPOCHS = 20
LEARNING_RATE = 0.00001

GPUs detected: ['/physical_device:GPU:0']
WARNING: WANDB_API_KEY not found in .env. Logging in anonymously.

wandb: Currently logged in as: pshashid (pshashid-university-of-maryland) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [ ]:
if __name__ == "__main__":
    try:
        print("--- Calling Data Preparation Pipeline from utils.py ---")
        train_gen, val_gen = utils.main_prep()

        print("\n--- Training Single ResNet50 Model ---")
        single_resnet = utils.train_model(train_gen, val_gen, architecture="ResNet50", epochs=NUM_EPOCHS, lr=LEARNING_RATE)
        print("\n--- Training Homogeneous Ensemble (ResNet50 x3) ---")
        models_homo, preds_homo, acc_homo = utils.homogeneous_ensemble(train_gen, val_gen, num_models=3, epochs=NUM_EPOCHS, lr=LEARNING_RATE)

        print("\n--- Training Heterogeneous Ensemble (ResNet50 + EfficientNetB0 + MobileNetV2) ---")
        architectures = ["ResNet50", "EfficientNetB0", "MobileNetV2"]
        models_hetero, preds_hetero, acc_hetero = utils.heterogeneous_ensemble(train_gen, val_gen, architectures, epochs=NUM_EPOCHS, lr=LEARNING_RATE)
    except Exception as e:
        print(f"\nAn error occurred during pipeline execution: {e}")
    finally:
        if wandb.run:
            wandb.finish()

--- Calling Data Preparation Pipeline from dataset_operations.py ---
--- Starting Data Preparation Pipeline ---
Downloading dataset: andrewmvd/animal-faces...
Using Colab cache for faster access to the 'animal-faces' dataset.
Path to dataset files: /kaggle/input/animal-faces

Collecting image paths and labels (performing Train/Validation Split)...

Train data collected. Samples: 14630

                                          image_path label
0  /kaggle/input/animal-faces/afhq/train/cat/pixa...   cat
1  /kaggle/input/animal-faces/afhq/train/cat/pixa...   cat
2  /kaggle/input/animal-faces/afhq/train/cat/pixa...   cat
3  /kaggle/input/animal-faces/afhq/train/cat/pixa...   cat
4  /kaggle/input/animal-faces/afhq/train/cat/flic...   cat

Validation data collected. Samples: 1500

                                          image_path label
0  /kaggle/input/animal-faces/afhq/val/cat/pixaba...   cat
1  /kaggle/input/animal-faces/afhq/val/cat/flickr...   cat
2  /kaggle/input/animal-faces/afhq/val/cat/flickr...   cat
3  /kaggle/input/animal-faces/afhq/val/cat/pixaba...   cat
4  /kaggle/input/animal-faces/afhq/val/cat/pixaba...   cat

Setting up ImageDataGenerators (including Data Augmentation)...
Found 14630 validated image filenames belonging to 3 classes.
Found 1500 validated image filenames belonging to 3 classes.
Data Augmentation applied. Generators created successfully.

--- Verification of Data Generators ---

[A] Location of Source Images (first 2 paths from train_df):
  - /kaggle/input/animal-faces/afhq/train/cat/pixabay_cat_000354.jpg
  - /kaggle/input/animal-faces/afhq/train/cat/pixabay_cat_002763.jpg
Total Source Images on Disk: 16130

[B] Generated Samples (Source Count) per Generator:
  - Training Samples (train_generator.samples): 14630
  - Validation Samples (val_generator.samples): 1500
  - Batch Size: 32

[B] Batches per Epoch (The number of times augmentation runs per epoch):
  - Training Steps per Epoch: 458
  - Validation Steps per Epoch: 47
--- Verification Complete ---

 Data Preparation Complete. Generators are ready for Transfer Learning.

--- Training Single ResNet50 Model ---

--- Training ResNet50 model ---

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

Epoch 1/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 123s 227ms/step - accuracy: 0.7386 - loss: 0.6127 - val_accuracy: 0.7007 - val_loss: 0.6662
Epoch 2/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.8918 - loss: 0.2848 - val_accuracy: 0.9080 - val_loss: 0.2490
Epoch 3/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.9080 - loss: 0.2439 - val_accuracy: 0.9020 - val_loss: 0.2399
Epoch 4/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.9105 - loss: 0.2383 - val_accuracy: 0.9027 - val_loss: 0.2521
Epoch 5/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.9208 - loss: 0.2057 - val_accuracy: 0.9380 - val_loss: 0.1941
Epoch 6/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9275 - loss: 0.1965 - val_accuracy: 0.9287 - val_loss: 0.1814
Epoch 7/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 187ms/step - accuracy: 0.9312 - loss: 0.1851 - val_accuracy: 0.9387 - val_loss: 0.1582
Epoch 8/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9348 - loss: 0.1700 - val_accuracy: 0.9400 - val_loss: 0.1582
Epoch 9/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.9350 - loss: 0.1743 - val_accuracy: 0.9407 - val_loss: 0.1645
Epoch 10/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.9376 - loss: 0.1616 - val_accuracy: 0.9407 - val_loss: 0.1569
Epoch 11/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 189ms/step - accuracy: 0.9394 - loss: 0.1542 - val_accuracy: 0.9267 - val_loss: 0.1905
Epoch 12/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9360 - loss: 0.1656 - val_accuracy: 0.9227 - val_loss: 0.2053
Epoch 13/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9488 - loss: 0.1390 - val_accuracy: 0.8900 - val_loss: 0.2862
Epoch 14/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.9444 - loss: 0.1453 - val_accuracy: 0.9373 - val_loss: 0.1565
Epoch 15/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9469 - loss: 0.1418 - val_accuracy: 0.8907 - val_loss: 0.2951
Epoch 16/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9498 - loss: 0.1341 - val_accuracy: 0.9520 - val_loss: 0.1417
Epoch 17/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9462 - loss: 0.1402 - val_accuracy: 0.9400 - val_loss: 0.1481
Epoch 18/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 191ms/step - accuracy: 0.9528 - loss: 0.1276 - val_accuracy: 0.9240 - val_loss: 0.2142
Epoch 19/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9529 - loss: 0.1295 - val_accuracy: 0.9373 - val_loss: 0.1656
Epoch 20/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9585 - loss: 0.1167 - val_accuracy: 0.9527 - val_loss: 0.1338
47/47 ━━━━━━━━━━━━━━━━━━━━ 4s 76ms/step - accuracy: 0.9455 - loss: 0.1595
ResNet50 Validation Accuracy: 0.9527

--- Training Homogeneous Ensemble (ResNet50 x3) ---

--- Training homogeneous model 1/3 ---

--- Training ResNet50 model ---
Epoch 1/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 124s 223ms/step - accuracy: 0.7812 - loss: 0.5279 - val_accuracy: 0.8573 - val_loss: 0.3406
Epoch 2/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 89s 194ms/step - accuracy: 0.8995 - loss: 0.2640 - val_accuracy: 0.9227 - val_loss: 0.2075
Epoch 3/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9073 - loss: 0.2368 - val_accuracy: 0.8887 - val_loss: 0.2610
Epoch 4/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9182 - loss: 0.2129 - val_accuracy: 0.9040 - val_loss: 0.2853
Epoch 5/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 193ms/step - accuracy: 0.9238 - loss: 0.1991 - val_accuracy: 0.9247 - val_loss: 0.1890
Epoch 6/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9262 - loss: 0.1955 - val_accuracy: 0.9427 - val_loss: 0.1568
Epoch 7/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9300 - loss: 0.1798 - val_accuracy: 0.8107 - val_loss: 0.5950
Epoch 8/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9314 - loss: 0.1790 - val_accuracy: 0.9360 - val_loss: 0.1677
Epoch 9/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9390 - loss: 0.1640 - val_accuracy: 0.9093 - val_loss: 0.2724
Epoch 10/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9367 - loss: 0.1690 - val_accuracy: 0.9320 - val_loss: 0.1855
Epoch 11/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9420 - loss: 0.1473 - val_accuracy: 0.8607 - val_loss: 0.4139
Epoch 12/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9427 - loss: 0.1517 - val_accuracy: 0.8820 - val_loss: 0.3153
Epoch 13/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9458 - loss: 0.1552 - val_accuracy: 0.7347 - val_loss: 0.8268
Epoch 14/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9436 - loss: 0.1446 - val_accuracy: 0.9480 - val_loss: 0.1468
Epoch 15/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 191ms/step - accuracy: 0.9461 - loss: 0.1417 - val_accuracy: 0.8033 - val_loss: 0.6464
Epoch 16/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9462 - loss: 0.1450 - val_accuracy: 0.7760 - val_loss: 0.7954
Epoch 17/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9509 - loss: 0.1336 - val_accuracy: 0.9027 - val_loss: 0.2735
Epoch 18/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 193ms/step - accuracy: 0.9425 - loss: 0.1473 - val_accuracy: 0.9400 - val_loss: 0.1742
Epoch 19/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 89s 193ms/step - accuracy: 0.9525 - loss: 0.1240 - val_accuracy: 0.9180 - val_loss: 0.2411
Epoch 20/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 193ms/step - accuracy: 0.9492 - loss: 0.1310 - val_accuracy: 0.9607 - val_loss: 0.1205
47/47 ━━━━━━━━━━━━━━━━━━━━ 4s 75ms/step - accuracy: 0.9612 - loss: 0.1282
ResNet50 Validation Accuracy: 0.9607

--- Training homogeneous model 2/3 ---

--- Training ResNet50 model ---
Epoch 1/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 123s 220ms/step - accuracy: 0.7857 - loss: 0.5153 - val_accuracy: 0.7600 - val_loss: 0.7416
Epoch 2/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.8975 - loss: 0.2656 - val_accuracy: 0.8953 - val_loss: 0.2720
Epoch 3/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9130 - loss: 0.2299 - val_accuracy: 0.9360 - val_loss: 0.1844
Epoch 4/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9216 - loss: 0.2089 - val_accuracy: 0.8033 - val_loss: 0.5558
Epoch 5/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9241 - loss: 0.2013 - val_accuracy: 0.9207 - val_loss: 0.1973
Epoch 6/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9351 - loss: 0.1762 - val_accuracy: 0.9180 - val_loss: 0.2309
Epoch 7/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9298 - loss: 0.1819 - val_accuracy: 0.9200 - val_loss: 0.2041
Epoch 8/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9313 - loss: 0.1817 - val_accuracy: 0.9020 - val_loss: 0.2541
Epoch 9/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9391 - loss: 0.1677 - val_accuracy: 0.8613 - val_loss: 0.3522
Epoch 10/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9399 - loss: 0.1572 - val_accuracy: 0.8680 - val_loss: 0.3523
Epoch 11/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 193ms/step - accuracy: 0.9425 - loss: 0.1490 - val_accuracy: 0.9473 - val_loss: 0.1441
Epoch 12/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9391 - loss: 0.1639 - val_accuracy: 0.9240 - val_loss: 0.2337
Epoch 13/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9441 - loss: 0.1555 - val_accuracy: 0.9220 - val_loss: 0.2002
Epoch 14/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9470 - loss: 0.1450 - val_accuracy: 0.9153 - val_loss: 0.2636
Epoch 15/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9462 - loss: 0.1433 - val_accuracy: 0.9320 - val_loss: 0.1727
Epoch 16/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9507 - loss: 0.1270 - val_accuracy: 0.9073 - val_loss: 0.2369
Epoch 17/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.9515 - loss: 0.1305 - val_accuracy: 0.8207 - val_loss: 0.5364
Epoch 18/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9530 - loss: 0.1318 - val_accuracy: 0.9527 - val_loss: 0.1407
Epoch 19/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.9519 - loss: 0.1279 - val_accuracy: 0.9160 - val_loss: 0.2319
Epoch 20/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 193ms/step - accuracy: 0.9523 - loss: 0.1309 - val_accuracy: 0.9187 - val_loss: 0.2476
47/47 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - accuracy: 0.9190 - loss: 0.2892
ResNet50 Validation Accuracy: 0.9187

--- Training homogeneous model 3/3 ---

--- Training ResNet50 model ---
Epoch 1/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 124s 222ms/step - accuracy: 0.7853 - loss: 0.5155 - val_accuracy: 0.9033 - val_loss: 0.2607
Epoch 2/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.8993 - loss: 0.2653 - val_accuracy: 0.9087 - val_loss: 0.2283
Epoch 3/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9148 - loss: 0.2275 - val_accuracy: 0.8227 - val_loss: 0.5603
Epoch 4/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9194 - loss: 0.2151 - val_accuracy: 0.8120 - val_loss: 0.5159
Epoch 5/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9256 - loss: 0.1969 - val_accuracy: 0.9160 - val_loss: 0.2100
Epoch 6/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.9338 - loss: 0.1806 - val_accuracy: 0.8267 - val_loss: 0.5382
Epoch 7/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9314 - loss: 0.1825 - val_accuracy: 0.9467 - val_loss: 0.1372
Epoch 8/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9334 - loss: 0.1759 - val_accuracy: 0.8687 - val_loss: 0.3395
Epoch 9/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9378 - loss: 0.1674 - val_accuracy: 0.8993 - val_loss: 0.2537
Epoch 10/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 191ms/step - accuracy: 0.9418 - loss: 0.1636 - val_accuracy: 0.8987 - val_loss: 0.2809
Epoch 11/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9451 - loss: 0.1509 - val_accuracy: 0.9280 - val_loss: 0.2053
Epoch 12/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9410 - loss: 0.1520 - val_accuracy: 0.8187 - val_loss: 0.4745
Epoch 13/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9438 - loss: 0.1483 - val_accuracy: 0.8500 - val_loss: 0.5376
Epoch 14/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9436 - loss: 0.1490 - val_accuracy: 0.9567 - val_loss: 0.1380
Epoch 15/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9465 - loss: 0.1393 - val_accuracy: 0.9313 - val_loss: 0.1826
Epoch 16/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.9537 - loss: 0.1284 - val_accuracy: 0.8973 - val_loss: 0.2729
Epoch 17/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9485 - loss: 0.1398 - val_accuracy: 0.9027 - val_loss: 0.3647
Epoch 18/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9509 - loss: 0.1276 - val_accuracy: 0.9307 - val_loss: 0.1874
Epoch 19/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9505 - loss: 0.1344 - val_accuracy: 0.9293 - val_loss: 0.1967
Epoch 20/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9479 - loss: 0.1349 - val_accuracy: 0.9153 - val_loss: 0.2260
47/47 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - accuracy: 0.9335 - loss: 0.1749
ResNet50 Validation Accuracy: 0.9153

--- Evaluating Ensemble ---
47/47 ━━━━━━━━━━━━━━━━━━━━ 12s 162ms/step
47/47 ━━━━━━━━━━━━━━━━━━━━ 11s 154ms/step
47/47 ━━━━━━━━━━━━━━━━━━━━ 11s 156ms/step
Ensemble Validation Accuracy: 0.9600

--- Training Heterogeneous Ensemble (ResNet50 + EfficientNetB0 + MobileNetV2) ---

--- Training ResNet50 model ---
Epoch 1/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 124s 223ms/step - accuracy: 0.7803 - loss: 0.5221 - val_accuracy: 0.8827 - val_loss: 0.3162
Epoch 2/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.8966 - loss: 0.2671 - val_accuracy: 0.9113 - val_loss: 0.2219
Epoch 3/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9171 - loss: 0.2220 - val_accuracy: 0.9220 - val_loss: 0.1998
Epoch 4/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9198 - loss: 0.2133 - val_accuracy: 0.9267 - val_loss: 0.1829
Epoch 5/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 192ms/step - accuracy: 0.9285 - loss: 0.1929 - val_accuracy: 0.9233 - val_loss: 0.2080
Epoch 6/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9212 - loss: 0.1931 - val_accuracy: 0.8847 - val_loss: 0.2857
Epoch 7/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9311 - loss: 0.1796 - val_accuracy: 0.9280 - val_loss: 0.1944
Epoch 8/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9386 - loss: 0.1646 - val_accuracy: 0.8713 - val_loss: 0.3462
Epoch 9/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 189ms/step - accuracy: 0.9325 - loss: 0.1702 - val_accuracy: 0.9440 - val_loss: 0.1527
Epoch 10/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9400 - loss: 0.1558 - val_accuracy: 0.9053 - val_loss: 0.2423
Epoch 11/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9382 - loss: 0.1652 - val_accuracy: 0.9260 - val_loss: 0.2011
Epoch 12/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 191ms/step - accuracy: 0.9392 - loss: 0.1602 - val_accuracy: 0.9180 - val_loss: 0.2129
Epoch 13/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 193ms/step - accuracy: 0.9413 - loss: 0.1577 - val_accuracy: 0.9140 - val_loss: 0.2265
Epoch 14/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 89s 194ms/step - accuracy: 0.9384 - loss: 0.1551 - val_accuracy: 0.9180 - val_loss: 0.2142
Epoch 15/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 89s 195ms/step - accuracy: 0.9446 - loss: 0.1473 - val_accuracy: 0.8340 - val_loss: 0.4690
Epoch 16/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 89s 195ms/step - accuracy: 0.9485 - loss: 0.1469 - val_accuracy: 0.9300 - val_loss: 0.1820
Epoch 17/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 90s 197ms/step - accuracy: 0.9497 - loss: 0.1325 - val_accuracy: 0.9473 - val_loss: 0.1450
Epoch 18/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9476 - loss: 0.1342 - val_accuracy: 0.8387 - val_loss: 0.5503
Epoch 19/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 193ms/step - accuracy: 0.9523 - loss: 0.1340 - val_accuracy: 0.8853 - val_loss: 0.3596
Epoch 20/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 88s 191ms/step - accuracy: 0.9492 - loss: 0.1331 - val_accuracy: 0.8633 - val_loss: 0.4148
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 73ms/step - accuracy: 0.9546 - loss: 0.1381
ResNet50 Validation Accuracy: 0.8633

--- Training EfficientNetB0 model ---
Downloading data from https://storage.googleapis.com/keras-applications/efficientnetb0_notop.h5
16705208/16705208 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
Epoch 1/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 167s 278ms/step - accuracy: 0.3622 - loss: 1.1066 - val_accuracy: 0.3373 - val_loss: 1.1558
Epoch 2/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.4205 - loss: 1.0617 - val_accuracy: 0.3420 - val_loss: 1.1543
Epoch 3/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.4624 - loss: 1.0252 - val_accuracy: 0.3587 - val_loss: 1.1500
Epoch 4/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.5009 - loss: 0.9749 - val_accuracy: 0.3673 - val_loss: 1.1812
Epoch 5/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.5233 - loss: 0.9373 - val_accuracy: 0.3600 - val_loss: 1.1999
Epoch 6/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.5444 - loss: 0.9084 - val_accuracy: 0.4007 - val_loss: 1.4497
Epoch 7/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.5546 - loss: 0.8918 - val_accuracy: 0.3560 - val_loss: 1.4240
Epoch 8/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.5631 - loss: 0.8714 - val_accuracy: 0.4173 - val_loss: 1.3763
Epoch 9/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 187ms/step - accuracy: 0.5880 - loss: 0.8424 - val_accuracy: 0.4073 - val_loss: 1.5526
Epoch 10/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.5794 - loss: 0.8477 - val_accuracy: 0.4633 - val_loss: 1.7221
Epoch 11/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.5951 - loss: 0.8276 - val_accuracy: 0.3947 - val_loss: 1.8652
Epoch 12/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 187ms/step - accuracy: 0.6086 - loss: 0.8171 - val_accuracy: 0.4507 - val_loss: 1.7827
Epoch 13/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.6159 - loss: 0.7989 - val_accuracy: 0.4093 - val_loss: 1.8806
Epoch 14/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 187ms/step - accuracy: 0.6230 - loss: 0.7791 - val_accuracy: 0.5593 - val_loss: 2.0319
Epoch 15/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.6216 - loss: 0.7830 - val_accuracy: 0.5773 - val_loss: 1.7887
Epoch 16/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 187ms/step - accuracy: 0.6314 - loss: 0.7695 - val_accuracy: 0.3707 - val_loss: 1.9710
Epoch 17/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 188ms/step - accuracy: 0.6272 - loss: 0.7821 - val_accuracy: 0.4127 - val_loss: 1.8623
Epoch 18/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 187ms/step - accuracy: 0.6315 - loss: 0.7679 - val_accuracy: 0.4927 - val_loss: 1.9564
Epoch 19/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 187ms/step - accuracy: 0.6345 - loss: 0.7603 - val_accuracy: 0.4127 - val_loss: 2.0871
Epoch 20/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 187ms/step - accuracy: 0.6455 - loss: 0.7525 - val_accuracy: 0.4120 - val_loss: 2.0369
47/47 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - accuracy: 0.3939 - loss: 0.9957
EfficientNetB0 Validation Accuracy: 0.4120

--- Training MobileNetV2 model ---
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_128_no_top.h5
9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
Epoch 1/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 141s 249ms/step - accuracy: 0.7912 - loss: 0.5181 - val_accuracy: 0.9860 - val_loss: 0.0605
Epoch 2/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.9731 - loss: 0.0843 - val_accuracy: 0.9913 - val_loss: 0.0327
Epoch 3/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.9809 - loss: 0.0561 - val_accuracy: 0.9913 - val_loss: 0.0326
Epoch 4/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.9865 - loss: 0.0425 - val_accuracy: 0.9927 - val_loss: 0.0223
Epoch 5/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.9909 - loss: 0.0301 - val_accuracy: 0.9920 - val_loss: 0.0205
Epoch 6/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.9912 - loss: 0.0262 - val_accuracy: 0.9927 - val_loss: 0.0202
Epoch 7/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.9896 - loss: 0.0281 - val_accuracy: 0.9927 - val_loss: 0.0196
Epoch 8/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.9918 - loss: 0.0227 - val_accuracy: 0.9933 - val_loss: 0.0190
Epoch 9/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 189ms/step - accuracy: 0.9924 - loss: 0.0217 - val_accuracy: 0.9947 - val_loss: 0.0183
Epoch 10/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9946 - loss: 0.0174 - val_accuracy: 0.9947 - val_loss: 0.0188
Epoch 11/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 185ms/step - accuracy: 0.9958 - loss: 0.0150 - val_accuracy: 0.9940 - val_loss: 0.0198
Epoch 12/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.9971 - loss: 0.0127 - val_accuracy: 0.9953 - val_loss: 0.0189
Epoch 13/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.9964 - loss: 0.0097 - val_accuracy: 0.9947 - val_loss: 0.0197
Epoch 14/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.9975 - loss: 0.0086 - val_accuracy: 0.9940 - val_loss: 0.0195
Epoch 15/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 85s 186ms/step - accuracy: 0.9981 - loss: 0.0096 - val_accuracy: 0.9940 - val_loss: 0.0202
Epoch 16/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 189ms/step - accuracy: 0.9971 - loss: 0.0090 - val_accuracy: 0.9940 - val_loss: 0.0198
Epoch 17/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 190ms/step - accuracy: 0.9977 - loss: 0.0074 - val_accuracy: 0.9953 - val_loss: 0.0166
Epoch 18/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 87s 189ms/step - accuracy: 0.9980 - loss: 0.0080 - val_accuracy: 0.9967 - val_loss: 0.0155
Epoch 19/20
458/458 ━━━━━━━━━━━━━━━━━━━━ 86s 187ms/step - accuracy: 0.9975 - loss: 0.0073 - val_accuracy: 0.9967 - val_loss: 0.0158
Epoch 20/20