# Imports

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import helpers.hgoogle_drive_api as hgodrapi

hgodrapi.install_needed_modules()

Module 'google' is already installed.
Module 'googleapiclient' is already installed.
Module 'gspread' is already installed.

In [3]:
import logging

import pandas as pd

# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option("future.no_silent_downcasting", True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hpandas as hpandas
import helpers.hprint as hprint

#
hdbg.init_logger(verbosity=logging.INFO)
_LOG = logging.getLogger(__name__)

#
_LOG.info("%s", henv.get_system_signature()[0])
hnotebook.config_notebook()

WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-4173c594-6e53-4544-8fcc-28228aced396.json'

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

INFO  # System signature
  # Container version
    container_version='2.0.0'
    changelog_version='2.2.0'
  # Git info
    branch_name='CsfyTask7819_Add_blogs'
    hash='3db7171293'
    # Last commits:
      * 3db7171293 GP Saggese Update                                                            (   4 hours ago) Tue Dec 23 22:51:16 2025  (HEAD -> CsfyTask7819_Add_blogs, origin/CsfyTask7819_Add_blogs)
      * 74bbbe5e4d GP Saggese Update                                                            (  11 hours ago) Tue Dec 23 16:12:47 2025
      * af867b645c GP Saggese Update                                                            (  11 hours ago) Tue Dec 23 15:19:41 2025
  # Platform info
    system=Linux
    node name=d89e94de37c3
    release=6.10.14-linuxkit
    version=#1 SMP Tue Apr 15 16:00:54 UTC 2025
    machine=aarch64
    processor=aarch64
  # psutils info
    cpu count=8
    cpu freq=None
    memory=svmem(total=16749285376, available=13652619264, percent=18.5, used=2833727488, free=12091748352, active=3491094528, inactive=741445632, buffers=261345280, cached=1562464256, shared=884736, slab=263966720)
    disk usage=sdiskusage(total=270233210880, used=154682195968, free=101790400512, percent=60.3)
  # Docker info
    has_docker=True
    docker_version='28.1.1'
    docker_needs_sudo=False
    has_privileged_mode=True
    is_inside_docker=True
    has_sibling_containers_support=True
    has_docker_dind_support=True
  # Packages
    python: 3.12.3
    cvxopt: 1.3.2
    cvxpy: 1.5.3
    gluonnlp: ?
    gluonts: ?
    joblib: 1.4.2
    mxnet: ?
    numpy: 2.1.3
    pandas: 2.2.3
    pyarrow: 18.0.0
    scipy: 1.14.1
    seaborn: 0.13.2
    sklearn: 1.5.2
    statsmodels: 0.14.4

In [4]:
import helpers.hgoogle_drive_api as hgodrapi

# Get credentials first.
credentials = hgodrapi.get_credentials(
    service_key_path="/home/.config/gspread_pandas/google_secret.json"
)

import ck_marketing.workflows as ckmktwf
import ck_marketing.plugins as ckmktpi

import importlib

importlib.reload(ckmktwf)
importlib.reload(ckmktpi)

gspread-gp
5.12.4
3.3.0

/app/ck_marketing/workflows/data_loaders.py:15: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

# Load Contact data

In [5]:
contact_dfs = []

In [6]:
normalize = True
# normalize = False
url = "https://docs.google.com/spreadsheets/d/1uSS5h5f3bcWxCFxg90TTB46296JgnFGQeKDaIKtz_84/edit?gid=2041749088#gid=2041749088"
tab_name = "LinkedIn_Profile_Scraper"
tag = "MA_targets_10k_persons"
df_tmp = ckmktwf.get_data_from_LinkedIn_Profile_Scraper(
    url, tab_name, tag, normalize
)

df_tmp.head(2)

INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1uSS5h5f3bcWxCFxg90TTB46296JgnFGQeKDaIKtz_84/edit?gid=2041749088#gid=2041749088'
  file_name='MA_targets_10k_persons'
  tab_name='LinkedIn_Profile_Scraper'

  hash                                         origin          origin_timestamp first_name last_name email email_timestamp email_verification email_verification_timestamp                        linkedin_url                             job_title company_name company_domain                                     city country enrichment_timestamp type                                          biography
0       PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:39.324Z      Fawaz     Ahmar                                                                        https://linkedin.com/in/fawazahmar   Senior Director - FS / M&A Advisory          PwC                       New York, New York, United States                                    Senior Director | FS / M&A Advisory | PwC; Faw...
1       PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:40.782Z      David  Popowitz                                                                          https://linkedin.com/in/popowitz  Vice President Corporate Development        Adobe                 Redwood City, California, United States                                    getting stuff done; Father of 3 boys -  mostly...

In [10]:
contact_dfs.append(df_tmp)

In [7]:
ckmktwf.print_contact_df_stats(df_tmp)

  hash                                         origin          origin_timestamp first_name last_name email email_timestamp email_verification email_verification_timestamp                        linkedin_url                            job_title company_name company_domain                               city country enrichment_timestamp type                                          biography
0       PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:39.324Z      Fawaz     Ahmar                                                                        https://linkedin.com/in/fawazahmar  Senior Director - FS / M&A Advisory          PwC                 New York, New York, United States                                    Senior Director | FS / M&A Advisory | PwC; Faw...

                                            0
num_rows                                  199
count_no_dups             199 / 199 = 100.00%
count_no_ascii             198 / 199 = 99.50%
count_email                   0 / 198 = 0.00%
count_email_verification      0 / 198 = 0.00%
count_name_dups               0 / 198 = 0.00%
count_origin              198 / 198 = 100.00%

# Concat all

In [11]:
print(len(contact_dfs))
# Contacts from LinkedIn connections might have no emails.
allow_no_emails = True
contact_df = pd.concat(contact_dfs)
debug = ""
# debug = "duplicated_emails"
# debug = "remove_chinese_names"
# debug = "remove_empty_first_name"
# debug = "clean_company_names"
# debug = "clean_linkedin_emails"
# debug = "clean_linkedin_websites"
contact_df = ckmktwf.clean_up_contact_df(
    contact_df, allow_no_emails=allow_no_emails, debug=debug
)
display(contact_df.head(2))

1

                                        0
duplicated_emails         0 / 199 = 0.00%
remove_invalid_emails     0 / 199 = 0.00%
remove_chinese_names      0 / 199 = 0.00%
remove_empty_first_names  0 / 199 = 0.00%
clean_company_names       0 / 199 = 0.00%
clean_linkedin_nans       0 / 199 = 0.00%
clean_linkedin_emails     0 / 199 = 0.00%
clean_linkedin_websites   0 / 199 = 0.00%
clean_emails              0 / 199 = 0.00%

                               hash                                         origin          origin_timestamp first_name last_name email email_timestamp email_verification email_verification_timestamp                        linkedin_url                             job_title company_name company_domain                                     city country enrichment_timestamp type                                          biography
0  8ae2fdf3ad9273ef1bad903f58feb87c  PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:39.324Z      Fawaz     Ahmar                                                                        https://linkedin.com/in/fawazahmar   Senior Director - FS / M&A Advisory          PwC                       New York, New York, United States                                    Senior Director | FS / M&A Advisory | PwC; Faw...
1  47c849671326a427e7f38a673777d278  PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:40.782Z      David  Popowitz                                                                          https://linkedin.com/in/popowitz  Vice President Corporate Development        Adobe                 Redwood City, California, United States                                    getting stuff done; Father of 3 boys -  mostly...

In [12]:
contact_df.iloc[0]

hash                                             8ae2fdf3ad9273ef1bad903f58feb87c
origin                              PB.LIN_Profile_Scraper.MA_targets_10k_persons
origin_timestamp                                         2025-12-24T00:29:39.324Z
first_name                                                                  Fawaz
last_name                                                                   Ahmar
email
email_timestamp
email_verification
email_verification_timestamp
linkedin_url                                   https://linkedin.com/in/fawazahmar
job_title                                     Senior Director - FS / M&A Advisory
company_name                                                                  PwC
company_domain
city                                            New York, New York, United States
country
enrichment_timestamp
type
biography                       Senior Director | FS / M&A Advisory | PwC; Faw...
Name: 0, dtype: object

In [13]:
ckmktwf.print_contact_df_detailed_stats(contact_df)

In [14]:
ckmktwf.sanity_check_contact_df(contact_df)

{'nan': 1.0}

In [15]:
ckmktwf.print_contact_df_stats(contact_df)

                               hash                                         origin          origin_timestamp first_name last_name email email_timestamp email_verification email_verification_timestamp                        linkedin_url                            job_title company_name company_domain                               city country enrichment_timestamp type                                          biography
0  8ae2fdf3ad9273ef1bad903f58feb87c  PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:39.324Z      Fawaz     Ahmar                                                                        https://linkedin.com/in/fawazahmar  Senior Director - FS / M&A Advisory          PwC                 New York, New York, United States                                    Senior Director | FS / M&A Advisory | PwC; Faw...

                                            0
num_rows                                  199
count_no_dups             199 / 199 = 100.00%
count_no_ascii             198 / 199 = 99.50%
count_email                   0 / 198 = 0.00%
count_email_verification      0 / 198 = 0.00%
count_name_dups               0 / 198 = 0.00%
count_origin              198 / 198 = 100.00%

In [16]:
contact_df["origin"].value_counts()

origin
PB.LIN_Profile_Scraper.MA_targets_10k_persons    199
Name: count, dtype: int64

In [17]:
# ckmktwf.save_to_gsheet(contact_df)

# Process Contact data

## Read data

In [ ]:
# assert 0

In [ ]:
if False:
    # url = "https://docs.google.com/spreadsheets/d/1nlfOHLUo2iTuNtFb2T5ZJXZZnztAnr3WzG9Jm5lbk6I"
    url = "https://docs.google.com/spreadsheets/d/1HanQiolicUToLgQFv1__cPOP4WLks5r7pHcgu2P8BjM"
    contact_df = ckmdatal.get_cached_sheet_to_df(url, "Sheet1")
    contact_df.set_index("hash", drop=True, inplace=True)
    #
    hpandas.head(contact_df)

In [ ]:
# contact_df = ckmktwf.clean_up_contact_df(contact_df,

In [ ]:
# ckmktwf.sanity_check_contact_df(contact_df)

In [ ]:
# ckmktwf.print_contact_df_stats(contact_df)

In [ ]:
# contact_df["origin"].value_counts()

In [ ]:
# stats_df = ckmktwf.print_contact_df_detailed_stats(contact_df)

## Clean up names

In [18]:
contact_df = ckmktpi.clean_and_track_name_changes(contact_df)

debug_df = ckmktpi.get_debug_clean_name_df(contact_df)
ckmktpi.get_clean_name_stats(contact_df)

  first_name last_name cleaned_first_name first_alias cleaned_last_name second_alias  is_modified
0      Fawaz     Ahmar              Fawaz                         Ahmar                     False
1      David  Popowitz              David                      Popowitz                     False
2     Manish    George             Manish                        George                     False

                                  0
is_modified       35 / 199 = 17.59%
empty_first_name    0 / 199 = 0.00%
empty_last_name     0 / 199 = 0.00%
has_alias           2 / 199 = 1.01%

In [20]:
hpandas.filter_df(debug_df, "is_modified", True).head(2)

INFO  selected=35 / 199 = 17.59%

   first_name            last_name cleaned_first_name first_alias cleaned_last_name second_alias  is_modified
4        Mike  Grabarek, SPHR, NCC               Mike                      Grabarek                      True
19     Pankaj       Soni, CFA, MBA             Pankaj                          Soni                      True

In [21]:
contact_df = ckmktpi.merge_clean_names_df(contact_df)

contact_df.head(1)

                               hash                                         origin          origin_timestamp first_name last_name email email_timestamp email_verification email_verification_timestamp                        linkedin_url                            job_title company_name company_domain                               city country enrichment_timestamp type                                          biography
0  8ae2fdf3ad9273ef1bad903f58feb87c  PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:39.324Z      Fawaz     Ahmar                                                                        https://linkedin.com/in/fawazahmar  Senior Director - FS / M&A Advisory          PwC                 New York, New York, United States                                    Senior Director | FS / M&A Advisory | PwC; Faw...

In [ ]:
# hgodrapi.to_gsheet(
#     hgodrapi.get_credentials(),
#     contact_df,
#     url: str,
#     freeze_rows=True,
# ) -> None:

In [22]:
# ckmktwf.save_to_gsheet(contact_df)

# Load into DB

In [23]:
db_path = "test.sql"

In [26]:
ckmktwf.get_table_count(db_path, "Contact")

INFO  Table 'Contact' has 3299 rows

3299

In [28]:
crm_df = ckmktwf.get_as_df(db_path, "Contact")

print(hpandas.head(crm_df))

shape=(3299, 19)

                               hash                    origin            origin_timestamp first_name last_name                     email             email_timestamp email_verification  \
0  c7aebb80a7bc2167ad058b8f6fae2fc5  Pitchbook.200AI.Corp_dev  2025-12-23 15:21:51.933500     Oliver   Steinig  oliver.steinig@bosch.com  2025-12-23 15:21:51.933500
1  2ebcc820c6e75eda4bba9b0ab579aeab  Pitchbook.200AI.Corp_dev  2025-12-23 15:21:51.933500    Harrick       Vin       harrick.vin@tcs.com  2025-12-23 15:21:51.933500

  email_verification_timestamp                                    linkedin_url                                                                job_title job_title_description  \
0                               http://linkedin.com/in/oliver-steinig-68603aa/  Vice President of Business Development and Corporate Strategy, Americas
1                                            http://linkedin.com/in/harrickvin                                                 Chief Technology Officer

                         company_name company_domain       city  country enrichment_timestamp type biography
0                  Bosch (Automotive)                 Gerlingen  Germany
1  Tata Consultancy Services (Mumbai)                    Mumbai    India

In [29]:
crm_df.origin.unique()

array(['Pitchbook.200AI.Corp_dev', 'Pitchbook.Fort500.Corp_dev'],
      dtype=object)

In [33]:
# mode = "assume_no_overlap"
mode = "keep_existing"
_ = ckmktwf.insert_contact_df(db_path, contact_df, mode)

In [34]:
crm_df = ckmktwf.get_as_df(db_path, "Contact")

print(hpandas.head(crm_df))
print(crm_df.origin.unique())

ckmktwf.get_table_count(db_path, "Contact")

shape=(199, 18)

                               hash                                         origin          origin_timestamp first_name last_name email email_timestamp email_verification  \
0  8ae2fdf3ad9273ef1bad903f58feb87c  PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:39.324Z      Fawaz     Ahmar
1  47c849671326a427e7f38a673777d278  PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:40.782Z      David  Popowitz

  email_verification_timestamp                        linkedin_url                             job_title company_name company_domain                                     city country  \
0                               https://linkedin.com/in/fawazahmar   Senior Director - FS / M&A Advisory          PwC                       New York, New York, United States
1                                 https://linkedin.com/in/popowitz  Vice President Corporate Development        Adobe                 Redwood City, California, United States

  enrichment_timestamp type  \
0
1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  biography
0  Senior Director | FS / M&A Advisory | PwC; Fawaz is an experienced Senior Director within the Financial Services and M&A Advisory consulting group at PwC with a focus on Deals and Technology Transformation and Corporate Development. His primary areas of expertise are integrations and separations, due diligence, technology strategy, digital transformation, project delivery and sales across multiple industries with significant experience in Banking, Capital Markets and Insurance. \n\nHe has led teams globally across the Americas, Europe and Asia and has extensive experience in mergers and acquisitions, divestitures, carve outs, data analytics and business transformation. \n\nHis client list as a Trusted Advisor includes global Financial Services institutions for leading Deals Transformation efforts in addition to top-tier Investment Banks / FinTechs where he has been involved in driving execution of their largest Regulatory Reform Programs on Wall Street.;
1                                                                                                                                                                                                                                                                                                                                                                           getting stuff done; Father of 3 boys -  mostly loud.\nTennis player, always working to improve my backhand.\nLove travel, biking and TED talks.\nEnjoy working with a great team to pursue partnerships and acquisitions that accelerate growth in a mission driven business.\nInvestor in many early stage technology companies\n\nSpecialties: Strategy, corporate transactions, negotiations, business development, team building and general management; Lead the corporate development and integration teams to accelerate Adobe's mission to help our customers imagine, create, and bring any digital experience to life
['PB.LIN_Profile_Scraper.MA_targets_10k_persons']
INFO  Table 'Contact' has 199 rows

199