# Install

In [1]:
if False:
    !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet jupyterlab-vim)"
    !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet gspread google-api-python-client google-auth-httplib2 google-auth-oauthlib)"
    !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet llm)"

# Import

In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [3]:
import logging

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hprint as hprint

print(henv.get_system_signature()[0])

hnotebook.config_notebook()

# hdbg.init_logger(verbosity=logging.DEBUG)
hdbg.init_logger(verbosity=logging.INFO)
# hdbg.test_logger()
_LOG = logging.getLogger(__name__)

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

# System signature
  # Container version
    container_version='2.0.0'
    changelog_version='2.2.0'
  # Git info
    branch_name='CsfyTask7819_Add_blogs'
    hash='9f727da4f3'
    # Last commits:
      * 9f727da4f3 GP Saggese Update                                                            (  13 hours ago) Sat Dec 20 01:09:54 2025  (HEAD -> CsfyTask7819_Add_blogs, origin/CsfyTask7819_Add_blogs)
      * 54a4ac1297 GP Saggese Update                                                            (  13 hours ago) Sat Dec 20 00:53:06 2025
      * ef630aedff GP Saggese Update                                                            (  25 hours ago) Fri Dec 19 12:27:11 2025
  # Platform info
    system=Linux
    node name=be5fb45cc44d
    release=6.10.14-linuxkit
    version=#1 SMP Tue Apr 15 16:00:54 UTC 2025
    machine=aarch64
    processor=aarch64
  # psutils info
    cpu count=8
    cpu freq=None
    memory=svmem(total=16749285376, available=14904229888, percent=11.0, used=1582166016, free=13704658944, active=1925193728, inactive=693608448, buffers=232431616, cached=1230028800, shared=880640, slab=258736128)
    disk usage=sdiskusage(total=270233210880, used=154690265088, free=101782331392, percent=60.3)
  # Docker info
    has_docker=True
    docker_version='28.1.1'
    docker_needs_sudo=False
    has_privileged_mode=True
    is_inside_docker=True
    has_sibling_containers_support=True
    has_docker_dind_support=True
  # Packages
    python: 3.12.3
    cvxopt: 1.3.2
    cvxpy: 1.5.3
    gluonnlp: ?
    gluonts: ?
    joblib: 1.4.2
    mxnet: ?
    numpy: 2.1.3
    pandas: 2.2.3
    pyarrow: 18.0.0
    scipy: 1.14.1
    seaborn: 0.13.2
    sklearn: 1.5.2
    statsmodels: 0.14.4
WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-f20f2452-e749-486d-a1f8-254373662e4c.json'

In [15]:
import importlib

import ck_marketing.workflows as ckmktwf
import ck_marketing.plugins as ckmktpi
import helpers.hgoogle_drive_api as hgodrapi

importlib.reload(ckmktwf)
importlib.reload(ckmktpi)

# Get credentials first
credentials = hgodrapi.get_credentials(
    service_key_path="/home/.config/gspread_pandas/google_secret.json"
)

# Load data

## From gsheet

In [5]:
# df = pb.load_49_companies_data()
# df = pb.load_200_companies_data()

# Pitchbook results for 200AICompanies.MA
# url = "https://docs.google.com/spreadsheets/d/1aKzWUw9mwP-2_vzz27ggeLe1sgF9OrWRWmGMo9Dk9bU/edit?gid=0#gid=0"
# tab_name = "200AICompanies.MA"
# df = ckmktpi.get_pitchbook_data_from_gsheet(url, tab_name)

# url = "https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws/edit?gid=2077123306#gid=2077123306"
# tab_name = "all"
# df = hgodrapi.from_gsheet(url, tab_name=tab_name, credentials=credentials)

# hpandas.head(df)

In [7]:
# Connect to MA on LinkedIn
url = "https://docs.google.com/spreadsheets/d/1tXnir8P5VjBxvbQOgJZmArRa7K__J7Fy90rWZtIxXTE/edit?gid=1167749805#gid=1167749805"

tab_name = "ConnectToLin-2025-12-16"
df = hgodrapi.from_gsheet(url, tab_name=tab_name, credentials=credentials)

hpandas.head(df)

columns= ['idx', 'People', 'LinkedInURL', 'LastName', 'FirstName', 'PrimaryCompany', 'PrimaryPosition', 'State/Province', 'Country/Territory/Region', 'Email', 'hunterio.email_verification', 'job_word', 'LIn_msg', 'EmailTxt', 'Merge status']
shape= (450, 15)

   idx        People                                      LinkedInURL LastName FirstName       PrimaryCompany                         PrimaryPosition State/Province Country/Territory/Region                      Email hunterio.email_verification               job_word                                            LIn_msg                                           EmailTxt   Merge status
0  127  Ki-Dong Park  http://kr.linkedin.com/in/ki-dong-park-29589316     Park   Ki-Dong  Samsung Electronics  Director, Corporate Strategic Planning       Gyeonggi              South Korea    kidong.park@samsung.com                       valid     strategic planning  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  EMAIL_CLICKED
1  128   Sarika Naik               http://linkedin.com/in/sarikanaik/     Naik    Sarika            Capgemini        Executive, Corporate Development                                  France  sarika.naik@capgemini.com                       valid  corporate development  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...     EMAIL_SENT

## Create LinkedIn messages

In [9]:
df.shape

(450, 15)

In [10]:
# Compute the job word.
if False:
    df2 = ckmktpi.apply_func_to_df(df, ckmktpi.get_job_word, "job_word")
else:
    df2 = df

hpandas.head(df2)

columns= ['idx', 'People', 'LinkedInURL', 'LastName', 'FirstName', 'PrimaryCompany', 'PrimaryPosition', 'State/Province', 'Country/Territory/Region', 'Email', 'hunterio.email_verification', 'job_word', 'LIn_msg', 'EmailTxt', 'Merge status']
shape= (450, 15)

   idx        People                                      LinkedInURL LastName FirstName       PrimaryCompany                         PrimaryPosition State/Province Country/Territory/Region                      Email hunterio.email_verification               job_word                                            LIn_msg                                           EmailTxt   Merge status
0  127  Ki-Dong Park  http://kr.linkedin.com/in/ki-dong-park-29589316     Park   Ki-Dong  Samsung Electronics  Director, Corporate Strategic Planning       Gyeonggi              South Korea    kidong.park@samsung.com                       valid     strategic planning  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  EMAIL_CLICKED
1  128   Sarika Naik               http://linkedin.com/in/sarikanaik/     Naik    Sarika            Capgemini        Executive, Corporate Development                                  France  sarika.naik@capgemini.com                       valid  corporate development  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...     EMAIL_SENT

In [20]:
# Compute the LinkedIn message.
df3 = ckmktpi.apply_func_to_df(df2, ckmktpi.get_LIn_connect_message, "LinText")

hpandas.head(df3)

  0%|          | 0/450 [00:00<?, ?it/s]

columns= ['idx', 'People', 'LinkedInURL', 'LastName', 'FirstName', 'PrimaryCompany', 'PrimaryPosition', 'State/Province', 'Country/Territory/Region', 'Email', 'hunterio.email_verification', 'job_word', 'LIn_msg', 'EmailTxt', 'Merge status', 'EmailText', 'LinText']
shape= (450, 17)

   idx        People                                      LinkedInURL LastName FirstName       PrimaryCompany                         PrimaryPosition State/Province Country/Territory/Region                      Email hunterio.email_verification               job_word                                            LIn_msg                                           EmailTxt   Merge status                                          EmailText                                            LinText
0  127  Ki-Dong Park  http://kr.linkedin.com/in/ki-dong-park-29589316     Park   Ki-Dong  Samsung Electronics  Director, Corporate Strategic Planning       Gyeonggi              South Korea    kidong.park@samsung.com                       valid     strategic planning  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  EMAIL_CLICKED  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...
1  128   Sarika Naik               http://linkedin.com/in/sarikanaik/     Naik    Sarika            Capgemini        Executive, Corporate Development                                  France  sarika.naik@capgemini.com                       valid  corporate development  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...     EMAIL_SENT  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...

In [21]:
# Compute the short email message.
df3 = ckmktpi.apply_func_to_df(
    df3, ckmktpi.get_email_connect_message, "EmailText"
)

hpandas.head(df3)

  0%|          | 0/450 [00:00<?, ?it/s]

columns= ['idx', 'People', 'LinkedInURL', 'LastName', 'FirstName', 'PrimaryCompany', 'PrimaryPosition', 'State/Province', 'Country/Territory/Region', 'Email', 'hunterio.email_verification', 'job_word', 'LIn_msg', 'EmailTxt', 'Merge status', 'EmailText', 'LinText']
shape= (450, 17)

   idx        People                                      LinkedInURL LastName FirstName       PrimaryCompany                         PrimaryPosition State/Province Country/Territory/Region                      Email hunterio.email_verification               job_word                                            LIn_msg                                           EmailTxt   Merge status                                          EmailText                                            LinText
0  127  Ki-Dong Park  http://kr.linkedin.com/in/ki-dong-park-29589316     Park   Ki-Dong  Samsung Electronics  Director, Corporate Strategic Planning       Gyeonggi              South Korea    kidong.park@samsung.com                       valid     strategic planning  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  EMAIL_CLICKED  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...  Hi Ki-Dong,\n\nI'm GP Saggese, and I teach AI ...
1  128   Sarika Naik               http://linkedin.com/in/sarikanaik/     Naik    Sarika            Capgemini        Executive, Corporate Development                                  France  sarika.naik@capgemini.com                       valid  corporate development  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...     EMAIL_SENT  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...  Hi Sarika,\n\nI'm GP Saggese, and I teach AI a...

In [ ]:
# print(ckmktpi.get_LIn_connect_message([df6.iloc[0]])[0])

In [22]:
# Save the results.
if True:
    # url = "https://docs.google.com/spreadsheets/d/1LYC46zrYJMpljaofxrBdrEDidwNSV6DwtljEzOxN8eY/edit?gid=0#gid=0"

    # tmp
    url = "https://docs.google.com/spreadsheets/d/1zB3p-bgRm_WDQbdMK-nfMeDDcrFtQI7YME4C5TsTBYU"
    hgodrapi.to_gsheet(df3, url, tab_name="before", freeze_rows=True, credentials=credentials)

INFO  Data written to the tab 'before' of the Google Sheet 'https://docs.google.com/spreadsheets/d/1zB3p-bgRm_WDQbdMK-nfMeDDcrFtQI7YME4C5TsTBYU

## Compute emails

In [ ]:
idx = 0
row = df.iloc[idx]

response = ckmktpi.get_email4(row)
# response = ckmktpi.get_email2(company_website, company_name)
# response = ckmktpi.get_business_descr(company_website, company_name)
print(response)

In [ ]:
df2 = ckmktpi.apply_func_to_df(
    df.iloc[100:300], ckmktpi.get_email5, "EmailText", batch_size=5
)
hpandas.head(df2)

In [ ]:
print(df2.iloc[0]["EmailText"])

In [ ]:
hpandas.head(df)

In [ ]:
df2 = ckmktpi.apply_func_to_df(df.iloc[300:], ckmktpi.get_email4, "EmailText")

hpandas.head(df2)

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1zB3p-bgRm_WDQbdMK-nfMeDDcrFtQI7YME4C5TsTBYU/edit?gid=604528158#gid=604528158"
hgodrapi.to_gsheet(df2, url, tab_name="final", credentials=credentials)