# Imports

In [128]:
# if False:
#     !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet jupyterlab-vim)"
#     !jupyter labextension enable
#     !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet --upgrade google-api-python-client)"

In [129]:
!cd /app

In [130]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [131]:
import helpers.hgoogle_drive_api as hgodrapi

hgodrapi.install_needed_modules()

Module 'google' is already installed.
Module 'googleapiclient' is already installed.
Module 'gspread' is already installed.

In [132]:
import logging

import pandas as pd

# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option("future.no_silent_downcasting", True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hpandas as hpandas
import helpers.hprint as hprint

#
hdbg.init_logger(verbosity=logging.INFO)
_LOG = logging.getLogger(__name__)

#
_LOG.info("%s", henv.get_system_signature()[0])
hnotebook.config_notebook()

WARNING: Logger already initialized: skipping
INFO  # System signature
  # Container version
    container_version='2.0.0'
    changelog_version='2.2.0'
  # Git info
    branch_name='CsfyTask7819_Add_blogs'
    hash='dde080aaa8'
    # Last commits:
      * dde080aaa8 GP Saggese Update                                                            (13 minutes ago) Wed Dec 24 16:22:33 2025  (HEAD -> CsfyTask7819_Add_blogs, origin/CsfyTask7819_Add_blogs)
      * aad6f8da37 GP Saggese Lint                                                              (  14 hours ago) Wed Dec 24 02:57:50 2025
      * 5fcf352882 GP Saggese Update                                                            (  14 hours ago) Wed Dec 24 02:55:48 2025
  # Platform info
    system=Linux
    node name=d89e94de37c3
    release=6.10.14-linuxkit
    version=#1 SMP Tue Apr 15 16:00:54 UTC 2025
    machine=aarch64
    processor=aarch64
  # psutils info
    cpu count=8
    cpu freq=None
    memory=svmem(total=16749285376, available=13303070720, percent=20.6, used=3183316992, free=11736768512, active=3834527744, inactive=743870464, buffers=264781824, cached=1564418048, shared=888832, slab=267345920)
    disk usage=sdiskusage(total=270233210880, used=154683105280, free=101789491200, percent=60.3)
  # Docker info
    has_docker=True
    docker_version='28.1.1'
    docker_needs_sudo=False
    has_privileged_mode=True
    is_inside_docker=True
    has_sibling_containers_support=True
    has_docker_dind_support=True
  # Packages
    python: 3.12.3
    cvxopt: 1.3.2
    cvxpy: 1.5.3
    gluonnlp: ?
    gluonts: ?
    joblib: 1.4.2
    mxnet: ?
    numpy: 2.1.3
    pandas: 2.2.3
    pyarrow: 18.0.0
    scipy: 1.14.1
    seaborn: 0.13.2
    sklearn: 1.5.2
    statsmodels: 0.14.4

In [133]:
import gspread
import gspread_pandas

# gspread_pandas.conf.get_config()
print(gspread_pandas.conf.get_config()["project_id"])
print(gspread.__version__)
print(gspread_pandas.__version__)

import helpers.hgoogle_drive_api as hgodrapi

# Get credentials first.
credentials = hgodrapi.get_credentials(
    service_key_path="/home/.config/gspread_pandas/google_secret.json"
)

import ck_marketing.workflows as ckmktwf
import ck_marketing.plugins as ckmktpi

import importlib

importlib.reload(ckmktwf)
importlib.reload(ckmktpi)

gspread-gp
5.12.4
3.3.0

# Load Contact data

In [134]:
contact_dfs = []

## Search4.FinTech_VC_in_US.SalesNavigator

In [135]:
normalize = True
df_tmp = ckmktwf.get_data_from_PB_SalesNavigator_Connections_Export(normalize)
contact_dfs.append(df_tmp)

In [136]:
ckmktwf.print_contact_df_stats(df_tmp)

  hash                    origin          origin_timestamp first_name last_name                    email email_timestamp email_verification email_verification_timestamp                                     linkedin_url job_title    company_name company_domain city country enrichment_timestamp type                                          biography
0       Search4.FinTech_VC_in_US  2023-11-09T20:34:20.691Z       Adam      Alfi  aalfi@iconiqcapital.com                                                                  https://www.linkedin.com/in/adam-alfi-52891823/   Partner  ICONIQ Capital                                                        Partner at ICONIQ / Growth Stage Technology In...

                                            0
num_rows                                  869
count_no_dups              867 / 869 = 99.77%
count_no_ascii            867 / 867 = 100.00%
count_email                465 / 867 = 53.63%
count_email_verification      0 / 867 = 0.00%
count_name_dups               0 / 867 = 0.00%
count_origin              867 / 867 = 100.00%

In [137]:
print(df_tmp.iloc[0])

hash
origin                                                   Search4.FinTech_VC_in_US
origin_timestamp                                         2023-11-09T20:34:20.691Z
first_name                                                                   Adam
last_name                                                                    Alfi
email                                                     aalfi@iconiqcapital.com
email_timestamp
email_verification
email_verification_timestamp
linkedin_url                      https://www.linkedin.com/in/adam-alfi-52891823/
job_title                                                                 Partner
company_name                                                       ICONIQ Capital
company_domain
city
country
enrichment_timestamp
type
biography                       Partner at ICONIQ / Growth Stage Technology In...
Name: 0, dtype: object

## VC_search_export

In [138]:
normalize = True
df_tmp = ckmktwf.get_data_from_LinkedIn2(normalize)
contact_dfs.append(df_tmp)

  0%|          | 0/11 [00:00<?, ?it/s]

In [139]:
ckmktwf.print_contact_df_stats(df_tmp)

  hash            origin          origin_timestamp first_name last_name               email email_timestamp email_verification email_verification_timestamp                                       linkedin_url job_title company_name company_domain                                  city country enrichment_timestamp type                                          biography
0       VC_search_export  2024-07-11T18:03:01.973Z     Zhenya   Loginov  zloginov@accel.com                            _valid_                               https://www.linkedin.com/in/ACwAAABGC0cBTaYzMW...   Partner        Accel                 Palo Alto, California, United States                                    I invest and help European and Israeli founder...

                                            0
num_rows                                  335
count_no_dups              287 / 335 = 85.67%
count_no_ascii             285 / 287 = 99.30%
count_email               285 / 285 = 100.00%
count_email_verification      0 / 285 = 0.00%
count_name_dups               2 / 285 = 0.70%
count_origin              285 / 285 = 100.00%

In [140]:
# ckmktwf.print_contact_df_detailed_stats(df_tmp)

## Search7.AI_VC_in_US.gsheet

In [141]:
normalize = True
# normalize = False
df_tmp = ckmktwf.get_data_from_LinkedIn3(normalize)
contact_dfs.append(df_tmp)

In [142]:
ckmktwf.print_contact_df_stats(df_tmp)

  hash               origin origin_timestamp first_name last_name           email email_timestamp email_verification email_verification_timestamp                           linkedin_url job_title      company_name company_domain city country enrichment_timestamp type biography
0       Search7.AI_VC_in_US                         Rob     Toews  rob@radical.vc                            _valid_                               https://www.linkedin.com/in/robtoews/            Radical Ventures

                                            0
num_rows                                  197
count_no_dups             197 / 197 = 100.00%
count_no_ascii            197 / 197 = 100.00%
count_email               197 / 197 = 100.00%
count_email_verification      0 / 197 = 0.00%
count_name_dups               0 / 197 = 0.00%
count_origin              197 / 197 = 100.00%

## VC Tier 1 - Partners

In [143]:
normalize = True
df_tmp = ckmktwf.get_data_from_VCSheet(normalize)
contact_dfs.append(df_tmp)

In [144]:
ckmktwf.print_contact_df_stats(df_tmp)

  hash          origin origin_timestamp first_name last_name              email email_timestamp email_verification email_verification_timestamp                         linkedin_url                      job_title company_name company_domain city country enrichment_timestamp type biography
0       VCSheet_Query1                         Ann  Miura-Ko  ann@floodgate.com                                                                  https://www.linkedin.com/in/amiura/  Co-Founding Partner@Floodgate    Floodgate

                                            0
num_rows                                  964
count_no_dups             964 / 964 = 100.00%
count_no_ascii             962 / 964 = 99.79%
count_email                890 / 962 = 92.52%
count_email_verification      0 / 962 = 0.00%
count_name_dups               1 / 962 = 0.10%
count_origin              962 / 962 = 100.00%

## VC_Tier_2_Partners

In [145]:
normalize = True
df_tmp = ckmktwf.get_data_from_LinkedIn5(normalize)
contact_dfs.append(df_tmp)

In [146]:
ckmktwf.print_contact_df_stats(df_tmp)

  hash     origin origin_timestamp first_name last_name                       email email_timestamp email_verification email_verification_timestamp linkedin_url job_title   company_name    company_domain                               city country enrichment_timestamp type biography
0       VC Tier 2                   Rodriguez      Keig  rodriguez@foundersfund.com                          _invalid_                                             Founder  Founders Fund  foundersfund.com  New York, New York, United States

                                            0
num_rows                                  253
count_no_dups              251 / 253 = 99.21%
count_no_ascii            251 / 251 = 100.00%
count_email               251 / 251 = 100.00%
count_email_verification      0 / 251 = 0.00%
count_name_dups               0 / 251 = 0.00%
count_origin              251 / 251 = 100.00%

## VCSheet

In [147]:
normalize = True
# normalize = False
df_tmp = ckmktwf.get_data_from_VCSheet(normalize)
contact_dfs.append(df_tmp)

In [148]:
ckmktwf.print_contact_df_stats(df_tmp)

  hash          origin origin_timestamp first_name last_name              email email_timestamp email_verification email_verification_timestamp                         linkedin_url                      job_title company_name company_domain city country enrichment_timestamp type biography
0       VCSheet_Query1                         Ann  Miura-Ko  ann@floodgate.com                                                                  https://www.linkedin.com/in/amiura/  Co-Founding Partner@Floodgate    Floodgate

                                            0
num_rows                                  964
count_no_dups             964 / 964 = 100.00%
count_no_ascii             962 / 964 = 99.79%
count_email                890 / 962 = 92.52%
count_email_verification      0 / 962 = 0.00%
count_name_dups               1 / 962 = 0.10%
count_origin              962 / 962 = 100.00%

## Euro-VCs

In [149]:
normalize = True
# normalize = False
df_tmp = ckmktwf.get_data_from_EuroVC(normalize)
contact_dfs.append(df_tmp)

In [150]:
ckmktwf.print_contact_df_stats(df_tmp)

  hash            origin          origin_timestamp first_name last_name email email_timestamp email_verification email_verification_timestamp                                 linkedin_url                 job_title                           company_name company_domain  city country enrichment_timestamp type biography
1       Euro-VC-LinkedIn  2020-08-20T16:15:48.000Z     Julian  Zachmann                                                                        https://www.linkedin.com/in/julianzachmann/  Venture Capital Investor  http://www.high-tech-gruenderfonds.de                 Bonn

                                            0
num_rows                                  557
count_no_dups              556 / 557 = 99.82%
count_no_ascii            556 / 556 = 100.00%
count_email                159 / 556 = 28.60%
count_email_verification      0 / 556 = 0.00%
count_name_dups               2 / 556 = 0.36%
count_origin              556 / 556 = 100.00%

## Folkapp

In [151]:
normalize = True
# normalize = False
df_tmp = ckmktwf.get_data_from_FolkApp(normalize)
contact_dfs.append(df_tmp)

In [152]:
ckmktwf.print_contact_df_stats(df_tmp)

  hash   origin origin_timestamp first_name  last_name                     email email_timestamp email_verification email_verification_timestamp                                linkedin_url                                       job_title     company_name company_domain       city country enrichment_timestamp type biography
0       Folkapp                       Susan  Akbarpour  susan@candouventures.com                                                                  https://www.linkedin.com/in/susanakbarpour  Investor, Serial entrepreneur and board member  Candou Ventures                 Palo Alto

                                              0
num_rows                                   2216
count_no_dups             2216 / 2216 = 100.00%
count_no_ascii             2213 / 2216 = 99.86%
count_email                2211 / 2213 = 99.91%
count_email_verification       0 / 2213 = 0.00%
count_name_dups                9 / 2213 = 0.41%
count_origin              2213 / 2213 = 100.00%

# Concat all

In [153]:
contact_df = pd.concat(contact_dfs)
debug = ""
# debug = "duplicated_emails"
# debug = "remove_chinese_names"
# debug = "remove_empty_first_name"
# debug = "clean_company_names"
# debug = "clean_linkedin_emails"
# debug = "clean_linkedin_websites"
contact_df = ckmktwf.clean_up_contact_df(contact_df, debug=debug)
display(contact_df.head(2))

                                             0
duplicated_emails         1234 / 6355 = 19.42%
remove_invalid_emails        10 / 5121 = 0.20%
remove_chinese_names          0 / 5111 = 0.00%
remove_empty_first_names      1 / 5111 = 0.02%
clean_company_names        539 / 5110 = 10.55%
clean_linkedin_nans           0 / 5110 = 0.00%
clean_linkedin_emails         1 / 5110 = 0.02%
clean_linkedin_websites       2 / 5110 = 0.04%
clean_emails                  0 / 5110 = 0.00%

                               hash                    origin          origin_timestamp first_name last_name                    email email_timestamp email_verification email_verification_timestamp                                     linkedin_url                              job_title    company_name company_domain city country enrichment_timestamp type                                          biography
0  ac52f900bfbdcf07070a1deb04ceaba4  Search4.FinTech_VC_in_US  2023-11-09T20:34:20.691Z       Adam      Alfi  aalfi@iconiqcapital.com                                                                  https://www.linkedin.com/in/adam-alfi-52891823/                                Partner  ICONIQ Capital                                                        Partner at ICONIQ / Growth Stage Technology In...
1  252520bb30bc09f55e92fdbfb6cf09e9  Search4.FinTech_VC_in_US  2023-11-10T05:33:23.329Z      Amman    Bhasin       abhasin@paypal.com                                                                         https://www.linkedin.com/in/ammanbhasin/  Investment Partner at PayPal Ventures          PayPal                                                        I'm excited by the rapid pace that technology ...

In [154]:
contact_df.iloc[0]

hash                                             ac52f900bfbdcf07070a1deb04ceaba4
origin                                                   Search4.FinTech_VC_in_US
origin_timestamp                                         2023-11-09T20:34:20.691Z
first_name                                                                   Adam
last_name                                                                    Alfi
email                                                     aalfi@iconiqcapital.com
email_timestamp
email_verification
email_verification_timestamp
linkedin_url                      https://www.linkedin.com/in/adam-alfi-52891823/
job_title                                                                 Partner
company_name                                                       ICONIQ Capital
company_domain
city
country
enrichment_timestamp
type
biography                       Partner at ICONIQ / Growth Stage Technology In...
Name: 0, dtype: object

In [155]:
ckmktwf.print_contact_df_detailed_stats(contact_df)

In [156]:
ckmktwf.sanity_check_contact_df(contact_df)

{'nan': 0.5246575342465754, 'match': 0.3913894324853229, 'mismatch': 0.08395303326810176}

In [157]:
ckmktwf.print_contact_df_stats(contact_df)

                               hash                    origin          origin_timestamp first_name last_name                    email email_timestamp email_verification email_verification_timestamp                                     linkedin_url job_title    company_name company_domain city country enrichment_timestamp type                                          biography
0  ac52f900bfbdcf07070a1deb04ceaba4  Search4.FinTech_VC_in_US  2023-11-09T20:34:20.691Z       Adam      Alfi  aalfi@iconiqcapital.com                                                                  https://www.linkedin.com/in/adam-alfi-52891823/   Partner  ICONIQ Capital                                                        Partner at ICONIQ / Growth Stage Technology In...

                                              0
num_rows                                   5110
count_no_dups              5033 / 5110 = 98.49%
count_no_ascii             5028 / 5033 = 99.90%
count_email                4159 / 5028 = 82.72%
count_email_verification       0 / 5028 = 0.00%
count_name_dups              187 / 5028 = 3.72%
count_origin              5028 / 5028 = 100.00%

In [158]:
display(contact_df["origin"].value_counts().to_frame())

                          count
origin
Folkapp                    2076
VCSheet_Query1              986
Search4.FinTech_VC_in_US    868
Euro-VC-LinkedIn            549
VC Tier 2                   229
VC_search_export            216
Search7.AI_VC_in_US         186

In [159]:
# ckmktwf.save_to_gsheet(contact_df)

# Process Contact data

## Clean up names

In [160]:
contact_df = ckmktpi.clean_and_track_name_changes(contact_df)

debug_df = ckmktpi.get_debug_clean_name_df(contact_df)
ckmktpi.get_clean_name_stats(contact_df)

  first_name last_name cleaned_first_name first_alias cleaned_last_name second_alias  is_modified
0       Adam      Alfi               Adam                          Alfi                     False
1      Amman    Bhasin              Amman                        Bhasin                     False
2       Andy   Canales               Andy                       Canales                     False

                                   0
is_modified       238 / 5110 = 4.66%
empty_first_name    4 / 5110 = 0.08%
empty_last_name     6 / 5110 = 0.12%
has_alias          21 / 5110 = 0.41%

In [161]:
hpandas.filter_df(debug_df, "is_modified", True).head(2)

INFO  selected=238 / 5110 = 4.66%

   first_name                 last_name cleaned_first_name first_alias  cleaned_last_name second_alias  is_modified
8     Alexsis         de Raadt St James            Alexsis              De Raadt St James                      True
10   Adrianna  Samaniego (she/her/ella)           Adrianna                      Samaniego                      True

In [162]:
contact_df = ckmktpi.merge_clean_names_df(contact_df)

contact_df.head(1)

                               hash                    origin          origin_timestamp first_name last_name                    email email_timestamp email_verification email_verification_timestamp                                     linkedin_url job_title    company_name company_domain city country enrichment_timestamp type                                          biography
0  ac52f900bfbdcf07070a1deb04ceaba4  Search4.FinTech_VC_in_US  2023-11-09T20:34:20.691Z       Adam      Alfi  aalfi@iconiqcapital.com                                                                  https://www.linkedin.com/in/adam-alfi-52891823/   Partner  ICONIQ Capital                                                        Partner at ICONIQ / Growth Stage Technology In...

In [163]:
# ckmktwf.save_to_gsheet(df)

# Load into DB

In [164]:
db_path = "test.sql"

In [165]:
# mode = "assume_no_overlap"
# mode = "assume_idempotent"
mode = "keep_new"
log_level = logging.DEBUG
df_out = ckmktwf.insert_contact_df(
    db_path, contact_df, mode, log_level=log_level
)

Inserting rows: 100%|██████████████████████████████████████████████████████████████████████████| 5110/5110 [00:00<00:00, 245292.16it/s]

In [166]:
ckmktwf.print_contact_stats(db_path)

Contact contact shape: (5186, 18)
Contact head:

                               hash                                         origin          origin_timestamp first_name last_name email email_timestamp email_verification email_verification_timestamp                        linkedin_url                            job_title company_name company_domain                               city country enrichment_timestamp type                                          biography
0  8ae2fdf3ad9273ef1bad903f58feb87c  PB.LIN_Profile_Scraper.MA_targets_10k_persons  2025-12-24T00:29:39.324Z      Fawaz     Ahmar                                                                        https://linkedin.com/in/fawazahmar  Senior Director - FS / M&A Advisory          PwC                 New York, New York, United States                                    Senior Director | FS / M&A Advisory | PwC; Faw...

                                               count
origin
Folkapp                                         2068
VCSheet_Query1                                   913
Search4.FinTech_VC_in_US                         842
Euro-VC-LinkedIn                                 547
VC Tier 2                                        223
VC_search_export                                 216
PB.LIN_Profile_Scraper.MA_targets_10k_persons    199
Search7.AI_VC_in_US                              178