# Install

In [6]:
if True:
    !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet jupyterlab-vim)"
    !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet gspread google-api-python-client google-auth-httplib2 google-auth-oauthlib)"
    !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet llm)"

# Import

In [7]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [8]:
import logging

import pandas as pd

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hprint as hprint

print(henv.get_system_signature()[0])

hnotebook.config_notebook()

# hdbg.init_logger(verbosity=logging.DEBUG)
hdbg.init_logger(verbosity=logging.INFO)
# hdbg.test_logger()
_LOG = logging.getLogger(__name__)

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

# System signature
  # Container version
    container_version='2.0.0'
    changelog_version='2.2.0'
  # Git info
    branch_name='CsfyTask7819_Add_blogs'
    hash='9f727da4f3'
    # Last commits:
      * 9f727da4f3 GP Saggese Update                                                            (35 minutes ago) Sat Dec 20 01:09:54 2025  (HEAD -> CsfyTask7819_Add_blogs, origin/CsfyTask7819_Add_blogs)
      * 54a4ac1297 GP Saggese Update                                                            (52 minutes ago) Sat Dec 20 00:53:06 2025
      * ef630aedff GP Saggese Update                                                            (  13 hours ago) Fri Dec 19 12:27:11 2025
  # Platform info
    system=Linux
    node name=be5fb45cc44d
    release=6.10.14-linuxkit
    version=#1 SMP Tue Apr 15 16:00:54 UTC 2025
    machine=aarch64
    processor=aarch64
  # psutils info
    cpu count=8
    cpu freq=None
    memory=svmem(total=16749285376, available=15227547648, percent=9.1, used=1258860544, free=14057508864, active=1546960896, inactive=686743552, buffers=230244352, cached=1202671616, shared=876544, slab=239632384)
    disk usage=sdiskusage(total=270233210880, used=154689380352, free=101783216128, percent=60.3)
  # Docker info
    has_docker=True
    docker_version='28.1.1'
    docker_needs_sudo=False
    has_privileged_mode=True
    is_inside_docker=True
    has_sibling_containers_support=True
    has_docker_dind_support=True
  # Packages
    python: 3.12.3
    cvxopt: 1.3.2
    cvxpy: 1.5.3
    gluonnlp: ?
    gluonts: ?
    joblib: 1.4.2
    mxnet: ?
    numpy: 2.1.3
    pandas: 2.2.3
    pyarrow: 18.0.0
    scipy: 1.14.1
    seaborn: 0.13.2
    sklearn: 1.5.2
    statsmodels: 0.14.4
WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-0aba6d96-12ea-4ce1-b563-743a63a3f539.json'

In [9]:
import importlib

import ck_marketing.workflows as ckmktwf
import ck_marketing.plugins as ckmktpi
import helpers.hgoogle_drive_api as hgodrapi

importlib.reload(ckmktwf)
importlib.reload(ckmktpi)

# Get credentials first
credentials = hgodrapi.get_credentials(
    service_key_path="/home/.config/gspread_pandas/google_secret.json"
)

/app/ck_marketing/workflows/data_loaders.py:15: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

# Load data

## From gsheet

In [4]:
# df = pb.load_49_companies_data()
# df = pb.load_200_companies_data()

# Pitchbook results for 200AICompanies.MA
# url = "https://docs.google.com/spreadsheets/d/1aKzWUw9mwP-2_vzz27ggeLe1sgF9OrWRWmGMo9Dk9bU/edit?gid=0#gid=0"
# tab_name = "200AICompanies.MA"
# df = ckmktpi.get_pitchbook_data_from_gsheet(url, tab_name)

# url = "https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws/edit?gid=2077123306#gid=2077123306"
# tab_name = "all"
# df = hgodrapi.from_gsheet(url, tab_name=tab_name, credentials=credentials)

# hpandas.head(df)

columns= ['idx', 'People', 'LinkedInURL', 'LastName', 'FirstName', 'PrimaryCompany', 'PrimaryPosition', 'State/Province', 'Country/Territory/Region', 'Email', 'hunterio.email_verification']
shape= (550, 11)

   idx      People                                   LinkedInURL LastName FirstName PrimaryCompany                                    PrimaryPosition State/Province Country/Territory/Region                      Email hunterio.email_verification
0  170  Anne Lebel  http://fr.linkedin.com/in/anne-lebel-b0a6245    Lebel      Anne      Capgemini  Chief Human Resources Officer, Group Executive...                                  France   anne.lebel@capgemini.com                  accept_all
1  149  Guy Sperry             http://linkedin.com/in/guysperry/   Sperry       Guy     Lucidworks                           Chief Technology Officer     California            United States  guy.sperry@lucidworks.com                       valid

In [6]:
# Connect to MA on LinkedIn
url = "https://docs.google.com/spreadsheets/d/1tXnir8P5VjBxvbQOgJZmArRa7K__J7Fy90rWZtIxXTE/edit?gid=1167749805#gid=1167749805"

tab_name = "ConnectToLin-2025-12-16"
df = hgodrapi.from_gsheet(url, tab_name=tab_name, credentials=credentials)

hpandas.head(df)

columns= ['idx', 'People', 'LinkedInURL', 'LastName', 'FirstName', 'PrimaryCompany', 'PrimaryPosition', 'State/Province', 'Country/Territory/Region', 'Email', 'hunterio.email_verification', 'job_word', 'LIn_msg']
shape= (450, 13)

   idx        People                                      LinkedInURL LastName FirstName       PrimaryCompany                         PrimaryPosition State/Province Country/Territory/Region                      Email hunterio.email_verification job_word LIn_msg
0  127  Ki-Dong Park  http://kr.linkedin.com/in/ki-dong-park-29589316     Park   Ki-Dong  Samsung Electronics  Director, Corporate Strategic Planning       Gyeonggi              South Korea    kidong.park@samsung.com                       valid
1  128   Sarika Naik               http://linkedin.com/in/sarikanaik/     Naik    Sarika            Capgemini        Executive, Corporate Development                                  France  sarika.naik@capgemini.com                       valid

## From CRM DB

In [10]:
# db_path = hgit.get_client_root(super_module=False) + "/../test.sql"
db_path = "test.sql"
print(db_path)

test.sql

In [11]:
contact_df = ckmktwf.get_as_df(db_path, "Contact_table")
hpandas.head(contact_df)

columns= ['hash', 'origin', 'origin_timestamp', 'first_name', 'last_name', 'email', 'email_timestamp', 'email_verification', 'email_verification_timestamp', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'country', 'enrichment_timestamp', 'type']
shape= (4347, 18)

                               hash                       origin            origin_timestamp first_name last_name                     email             email_timestamp email_verification email_verification_timestamp                                    linkedin_url                                          job_title job_title_description                        company_name company_domain       city  country enrichment_timestamp type
0  c7aebb80a7bc2167ad058b8f6fae2fc5  Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783     Oliver   Steinig  oliver.steinig@bosch.com  2025-12-15 16:53:07.146783                                                  http://linkedin.com/in/oliver-steinig-68603aa/  Vice President of Business Development and Cor...                                        Bosch (Automotive)                 Gerlingen  Germany
1  2ebcc820c6e75eda4bba9b0ab579aeab  Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783    Harrick       Vin       harrick.vin@tcs.com  2025-12-15 16:53:07.146783                                                               http://linkedin.com/in/harrickvin                           Chief Technology Officer                        Tata Consultancy Services (Mumbai)                    Mumbai    India

In [12]:
origin = "Pitchbook.200AICompanies.MA"

mask = contact_df["origin"] == origin
print(mask.sum())
contact_df2 = contact_df[mask]

hpandas.head(contact_df2)

718
columns= ['hash', 'origin', 'origin_timestamp', 'first_name', 'last_name', 'email', 'email_timestamp', 'email_verification', 'email_verification_timestamp', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'country', 'enrichment_timestamp', 'type']
shape= (718, 18)

                               hash                       origin            origin_timestamp first_name last_name                     email             email_timestamp email_verification email_verification_timestamp                                    linkedin_url                                          job_title job_title_description                        company_name company_domain       city  country enrichment_timestamp type
0  c7aebb80a7bc2167ad058b8f6fae2fc5  Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783     Oliver   Steinig  oliver.steinig@bosch.com  2025-12-15 16:53:07.146783                                                  http://linkedin.com/in/oliver-steinig-68603aa/  Vice President of Business Development and Cor...                                        Bosch (Automotive)                 Gerlingen  Germany
1  2ebcc820c6e75eda4bba9b0ab579aeab  Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783    Harrick       Vin       harrick.vin@tcs.com  2025-12-15 16:53:07.146783                                                               http://linkedin.com/in/harrickvin                           Chief Technology Officer                        Tata Consultancy Services (Mumbai)                    Mumbai    India

In [21]:
id_ = 1
name = "Contact via email Pitchbook.200AICompanies.MA"
type_ = "email"
description = ""
message = ""
start_date = pd.Timestamp.now()
campaign_targets = ckmktwf.create_campaign_target_from_df(contact_df2, "email")

INFO  Created 718 campaign targets

In [22]:
ckmktwf.create_campaign_target_table(
    db_path, id_, name, type_, description, message, start_date, campaign_targets
)

INFO  Creating campaign 'Contact via email Pitchbook.200AICompanies.MA' with 718 targets

Inserting campaign targets: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 718/718 [00:00<00:00, 170885.22it/s]

INFO  Campaign 'Contact via email Pitchbook.200AICompanies.MA' (id=1) created successfully with 718 targets

1

# Clean up

## Remove invalid emails

In [7]:
df = ckmktpi.remove_invalid_emails(df, verbose=False)
hpandas.head(df)

INFO  Removed emails: 0 / 450 = 0.00%
columns= ['idx', 'People', 'LinkedInURL', 'LastName', 'FirstName', 'PrimaryCompany', 'PrimaryPosition', 'State/Province', 'Country/Territory/Region', 'Email', 'hunterio.email_verification', 'job_word', 'LIn_msg']
shape= (450, 13)

   idx        People                                      LinkedInURL LastName FirstName       PrimaryCompany                         PrimaryPosition State/Province Country/Territory/Region                      Email hunterio.email_verification job_word LIn_msg
0  127  Ki-Dong Park  http://kr.linkedin.com/in/ki-dong-park-29589316     Park   Ki-Dong  Samsung Electronics  Director, Corporate Strategic Planning       Gyeonggi              South Korea    kidong.park@samsung.com                       valid
1  128   Sarika Naik               http://linkedin.com/in/sarikanaik/     Naik    Sarika            Capgemini        Executive, Corporate Development                                  France  sarika.naik@capgemini.com                       valid

In [8]:
df.iloc[0]

idx                                                                        127
People                                                            Ki-Dong Park
LinkedInURL                    http://kr.linkedin.com/in/ki-dong-park-29589316
LastName                                                                  Park
FirstName                                                              Ki-Dong
PrimaryCompany                                             Samsung Electronics
PrimaryPosition                         Director, Corporate Strategic Planning
State/Province                                                        Gyeonggi
Country/Territory/Region                                           South Korea
Email                                                  kidong.park@samsung.com
hunterio.email_verification                                              valid
job_word
LIn_msg
Name: 0, dtype: object

## Validate emails

In [ ]:
# os.environ["HUNTER_API_KEY"] = "c5e3c68e63e52a0e2ca088e8c73a95220cd5ba48"

# ckmktpi.get_hunterio_account_info()

In [ ]:
# df2 = ckmktpi.hunterio_verify_emails_from_df(df, email_col="Email")
# hpandas.head(df2)

In [ ]:
# df2["hunterio.email_verification"].unique()

In [ ]:
# Print stats.
# stats_dict = ckmktpi.get_email_stats(df2, "hunterio.email_verification", is_email_verification=True)
# pprint.pprint(stats_dict)

In [ ]:
# df3 = ckmktpi.remove_invalid_emails_from_hunterio_df(df2)

# hpandas.head(df3)

## Process

In [ ]:
# url = "https://docs.google.com/spreadsheets/d/1LYC46zrYJMpljaofxrBdrEDidwNSV6DwtljEzOxN8eY/edit?gid=0#gid=0"

if False:
    # tmp
    url = "https://docs.google.com/spreadsheets/d/1zB3p-bgRm_WDQbdMK-nfMeDDcrFtQI7YME4C5TsTBYU"
    hgodrapi.to_gsheet(df, url, tab_name="before", freeze_rows=True, credentials=credentials)

In [10]:
# OpenAI client logging
logging.getLogger("openai").setLevel(logging.WARNING)

# Common HTTP logging sources
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpcore").setLevel(logging.WARNING)
logging.getLogger("urllib3").setLevel(logging.WARNING)

## Create LinkedIn messages

In [ ]:
assert 0

In [11]:
df.shape

(450, 13)

In [12]:
# df6 = ckmktpi.apply_func_to_df(df5.iloc[0:100], ckmktpi.get_job_word, "job_word")
df6 = ckmktpi.apply_func_to_df(df, ckmktpi.get_job_word, "job_word")

hpandas.head(df6)

  0%|          | 0/450 [00:00<?, ?it/s]

columns= ['idx', 'People', 'LinkedInURL', 'LastName', 'FirstName', 'PrimaryCompany', 'PrimaryPosition', 'State/Province', 'Country/Territory/Region', 'Email', 'hunterio.email_verification', 'job_word', 'LIn_msg']
shape= (450, 13)

   idx        People                                      LinkedInURL LastName FirstName       PrimaryCompany                         PrimaryPosition State/Province Country/Territory/Region                      Email hunterio.email_verification               job_word LIn_msg
0  127  Ki-Dong Park  http://kr.linkedin.com/in/ki-dong-park-29589316     Park   Ki-Dong  Samsung Electronics  Director, Corporate Strategic Planning       Gyeonggi              South Korea    kidong.park@samsung.com                       valid     strategic planning
1  128   Sarika Naik               http://linkedin.com/in/sarikanaik/     Naik    Sarika            Capgemini        Executive, Corporate Development                                  France  sarika.naik@capgemini.com                       valid  corporate development

In [23]:
df7 = ckmktpi.apply_func_to_df(df6, ckmktpi.get_LIn_connect_message, "LIn_msg")

hpandas.head(df7)

NameError: name 'df6' is not defined

In [20]:
print(ckmktpi.get_LIn_connect_message([df6.iloc[0]])[0])

Hi Ki-Dong,

I'm GP Saggese, and I teach AI at the Univ of Maryland, doing research on
causal AI and LLMs.

Given your work at Samsung Electronics in strategic planning, I thought to connect with you.

Here is my LinkedIn profile: https://www.linkedin.com/in/gpsaggese/
Please feel free to connect with me.

Thanks,
GP

In [21]:
# url = "https://docs.google.com/spreadsheets/d/1LYC46zrYJMpljaofxrBdrEDidwNSV6DwtljEzOxN8eY/edit?gid=0#gid=0"

# tmp
url = "https://docs.google.com/spreadsheets/d/1zB3p-bgRm_WDQbdMK-nfMeDDcrFtQI7YME4C5TsTBYU"
hgodrapi.to_gsheet(df7, url, tab_name="before", freeze_rows=True, credentials=credentials)

INFO  Data written to the tab 'before' of the Google Sheet 'https://docs.google.com/spreadsheets/d/1zB3p-bgRm_WDQbdMK-nfMeDDcrFtQI7YME4C5TsTBYU

## Compute emails

In [ ]:
idx = 0
row = df.iloc[idx]

response = ckmktpi.get_email4(row)
# response = ckmktpi.get_email2(company_website, company_name)
# response = ckmktpi.get_business_descr(company_website, company_name)
print(response)

In [ ]:
df2 = ckmktpi.apply_func_to_df(
    df.iloc[100:300], ckmktpi.get_email5, "EmailText", batch_size=5
)
hpandas.head(df2)

In [ ]:
print(df2.iloc[0]["EmailText"])

In [ ]:
hpandas.head(df)

In [ ]:
df2 = ckmktpi.apply_func_to_df(df.iloc[300:], ckmktpi.get_email4, "EmailText")

hpandas.head(df2)

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1zB3p-bgRm_WDQbdMK-nfMeDDcrFtQI7YME4C5TsTBYU/edit?gid=604528158#gid=604528158"
hgodrapi.to_gsheet(df2, url, tab_name="final", credentials=credentials)