# Imports

In [1]:
# !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet jupyterlab-vim)"
# !jupyter labextension enable

#!sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet --upgrade google-api-python-client)"

In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import logging

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hprint as hprint

hdbg.init_logger(verbosity=logging.INFO)
_LOG = logging.getLogger(__name__)
_LOG.info("%s", henv.get_system_signature()[0])

hnotebook.config_notebook()

WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-8ca75ec3-f172-441e-bfdb-5e7d4dc699fe.json'

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

INFO  # System signature
  # Container version
    container_version='2.0.0'
    changelog_version='2.2.0'
  # Git info
    branch_name='CsfyTask7819_Add_blogs'
    hash='479c99479'
    # Last commits:
      * 479c99479 GP Saggese Update                                                            (  12 hours ago) Fri Dec 19 12:13:01 2025  (HEAD -> CsfyTask7819_Add_blogs, origin/CsfyTask7819_Add_blogs)
      * d11ac6550 GP Saggese Update                                                            (  12 hours ago) Fri Dec 19 12:08:25 2025
      * 069b5dd84 GP Saggese Update                                                            (  12 hours ago) Fri Dec 19 12:04:20 2025
  # Platform info
    system=Linux
    node name=581253e6cff0
    release=6.10.14-linuxkit
    version=#1 SMP Tue Apr 15 16:00:54 UTC 2025
    machine=aarch64
    processor=aarch64
  # psutils info
    cpu count=8
    cpu freq=None
    memory=svmem(total=16749285376, available=9842814976, percent=41.2, used=6643523584, free=7878905856, active=7374696448, inactive=972292096, buffers=428220416, cached=1798635520, shared=888832, slab=343531520)
    disk usage=sdiskusage(total=270233210880, used=154688589824, free=101784006656, percent=60.3)
  # Docker info
    has_docker=True
    docker_version='28.1.1'
    docker_needs_sudo=False
    has_privileged_mode=True
    is_inside_docker=True
    has_sibling_containers_support=True
    has_docker_dind_support=True
  # Packages
    python: 3.12.3
    cvxopt: 1.3.2
    cvxpy: 1.5.3
    gluonnlp: ?
    gluonts: ?
    joblib: 1.4.2
    mxnet: ?
    numpy: 2.1.3
    pandas: 2.2.3
    pyarrow: 18.0.0
    scipy: 1.14.1
    seaborn: 0.13.2
    sklearn: 1.5.2
    statsmodels: 0.14.4

In [4]:
import pandas as pd

import helpers.hgoogle_drive_api as hgodrapi

# Get credentials.
credentials = hgodrapi.get_credentials(
    service_key_path="/home/.config/gspread_pandas/google_secret.json"
)

In [5]:
import importlib

import ck_marketing.workflows as ckmktwf

importlib.reload(ckmktwf)

/app/ck_marketing/workflows/data_loaders.py:15: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

In [6]:
db_path = "test.sql"

In [7]:
ckmktwf.print_table_schema(db_path, print_schema=False)

================================================================================
Table: Contact_table
================================================================================

Row count: 4347

================================================================================
Table: LinkedIn_table
================================================================================

Row count: 0

================================================================================

In [8]:
ckmktwf.print_table_schema(db_path, tables=["Contact_table"])

================================================================================
Table: Contact_table
================================================================================

Row count: 4347

================================================================================

In [9]:
ckmktwf.get_contact_count(db_path)

4347

In [10]:
contact_df = ckmktwf.get_as_df(db_path, "Contact_table")
hpandas.head(contact_df)

columns= ['hash', 'origin', 'origin_timestamp', 'first_name', 'last_name', 'email', 'email_timestamp', 'email_verification', 'email_verification_timestamp', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'country', 'enrichment_timestamp', 'type']
shape= (4347, 18)

                               hash                       origin            origin_timestamp first_name last_name                     email             email_timestamp email_verification email_verification_timestamp                                    linkedin_url                                          job_title job_title_description                        company_name company_domain       city  country enrichment_timestamp type
0  c7aebb80a7bc2167ad058b8f6fae2fc5  Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783     Oliver   Steinig  oliver.steinig@bosch.com  2025-12-15 16:53:07.146783                                                  http://linkedin.com/in/oliver-steinig-68603aa/  Vice President of Business Development and Cor...                                        Bosch (Automotive)                 Gerlingen  Germany
1  2ebcc820c6e75eda4bba9b0ab579aeab  Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783    Harrick       Vin       harrick.vin@tcs.com  2025-12-15 16:53:07.146783                                                               http://linkedin.com/in/harrickvin                           Chief Technology Officer                        Tata Consultancy Services (Mumbai)                    Mumbai    India

# Read a Yamm campaign

In [11]:
urls = [
    (
        "https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws/edit?gid=0#gid=0",
        "Sheet1",
    ),
    (
        "https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws/edit?gid=0#gid=0",
        "Sheet2",
    ),
    # ("https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws/edit?gid=0#gid=0", "2025-12-12"),
]

# Extract the BOUNCED and mark it as "yamm.bounced".
url, tab_name = urls[0]
print(url)
normalize = True

yamm_df = hgodrapi.from_gsheet(url, tab_name=tab_name, credentials=credentials)

https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws/edit?gid=0#gid=0

In [12]:
contact_df.head(2)

                               hash                       origin            origin_timestamp first_name last_name                     email             email_timestamp email_verification email_verification_timestamp                                    linkedin_url                                          job_title job_title_description                        company_name company_domain       city  country enrichment_timestamp type
0  c7aebb80a7bc2167ad058b8f6fae2fc5  Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783     Oliver   Steinig  oliver.steinig@bosch.com  2025-12-15 16:53:07.146783                                                  http://linkedin.com/in/oliver-steinig-68603aa/  Vice President of Business Development and Cor...                                        Bosch (Automotive)                 Gerlingen  Germany
1  2ebcc820c6e75eda4bba9b0ab579aeab  Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783    Harrick       Vin       harrick.vin@tcs.com  2025-12-15 16:53:07.146783                                                               http://linkedin.com/in/harrickvin                           Chief Technology Officer                        Tata Consultancy Services (Mumbai)                    Mumbai    India

In [13]:
yamm_df.head(2)

   idx          People                                      LinkedInURL  LastName FirstName PrimaryCompany                                 PrimaryPosition State/Province Country/Territory/Region                         Email                                          EmailText Merge status
0  165  David Schmaier  http://linkedin.com/in/david-schmaier-70476b43/  Schmaier     David     Salesforce              President & Chief Strategy Officer     California            United States  davidschmaier@salesforce.com  Hi David,\n\nI’m GP Saggese, CTO of Causify.AI...   EMAIL_SENT
1  512   Assaf Feldman   http://il.linkedin.com/in/assaf-feldman-991167   Feldman     Assaf      Riskified  Chief Technology Officer, Technology & Founder                                  Israel           assaf@riskified.com  Hi Assaf,\n\nI’m GP Saggese, CTO of Causify.AI...   EMAIL_SENT

In [16]:
timestamp = pd.Timestamp.now()
out_df = ckmktwf.update_df_with_yamm_bounced(
    contact_df,
    yamm_df,
    timestamp,
    email_col1="email",
    email_col2="Email",
    yamm_col="Merge status",
)

INFO  Updating contact df (4347 rows) with YAMM results (83 rows)
INFO  Changed state to _yamm_bounced_: 0 -> 25

In [15]:
out_df

                                  hash                                             origin            origin_timestamp first_name   last_name                          email             email_timestamp email_verification email_verification_timestamp                                       linkedin_url                                          job_title job_title_description                        company_name company_domain           city        country enrichment_timestamp type  yamm.bounced
0     c7aebb80a7bc2167ad058b8f6fae2fc5                        Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783     Oliver     Steinig       oliver.steinig@bosch.com  2025-12-15 16:53:07.146783                                                     http://linkedin.com/in/oliver-steinig-68603aa/  Vice President of Business Development and Cor...                                        Bosch (Automotive)                     Gerlingen        Germany                                   False
1     2ebcc820c6e75eda4bba9b0ab579aeab                        Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783    Harrick         Vin            harrick.vin@tcs.com  2025-12-15 16:53:07.146783                                                                  http://linkedin.com/in/harrickvin                           Chief Technology Officer                        Tata Consultancy Services (Mumbai)                        Mumbai          India                                   False
2     84c02c36f77bde79492236663fcb35c6                        Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783       Alok   Paranjpye  alok.paranjpye@servicenow.com  2025-12-15 16:53:07.146783                                                               http://linkedin.com/in/alokparanjpye                 Vice President, Corporate Strategy                                                ServiceNow                   Santa Clara  United States                                   False
3     d59a24901c57794b1b481cd9eb936cd8                        Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783     YouJin         Nam         youjin.nam@samsung.com  2025-12-15 16:53:07.146783                                                  http://kr.linkedin.com/in/youjin-nam-���������...  Director of Tech Strategic Planning, Samsung R...                                       Samsung Electronics                         Suwon    South Korea                                   False
4     69f30b022a3baf03ea1f7eb699289404                        Pitchbook.200AICompanies.MA  2025-12-15 16:53:07.146783     Curtis         Liu       curtis.liu@amplitude.com  2025-12-15 16:53:07.146783                                                                   http://linkedin.com/in/curtisliu  Chief Technology Officer, Board Member & Co-Fo...                                                 Amplitude                 San Francisco  United States                                   False
...                                ...                                                ...                         ...        ...         ...                            ...                         ...                ...                          ...                                                ...                                                ...                   ...                                 ...            ...            ...            ...                  ...  ...           ...
4342  4f1935d4f70ee0dc0f8427fdf27d84ff  PB.LIN_Connections_Exports.GP_Lin_Connections_...    2025-12-09T23:57:35.192Z      Navya      Bansal                                   2025-12-09T23:57:35.192Z                                                            https://www.linkedin.com/in/novabansal/  Protein Engineering / Design Co-Op @ NextCure ...                                                                                                                                          False
4343  b1e08b0177198dfe54ab7ede693fd682  PB.LIN_Connections_Exports.GP_Lin_Connections_...    2025-12-09T23:57:35.192Z       Karl     Leodler                                   2025-12-09T23:57:35.192Z                                                  https://www.linkedin.com/in/karl-leodler-a804068/                     Dynamic Dimension Technologies                                                                                                                                          False
4344  9e565b4260c50f68770a340eaf8d2755  PB.LIN_Connections_Exports.GP_Lin_Connections_...    2025-12-09T23:57:35.192Z    Vinayak       Dhruv                                   2025-12-09T23:57:35.192Z                                                  https://www.linkedin.com/in/vinayak-dhruv-a257...  Enterprise LLMs & Agentic AI @ Cohere | AI Res...                                                                                                                                          False
4345  b2b3dad319c174d6ce2d51cbc17d062c  PB.LIN_Connections_Exports.GP_Lin_Connections_...    2025-12-09T23:57:35.192Z      Parth  Maheshwari                                   2025-12-09T23:57:35.192Z                                                  https://www.linkedin.com/in/parth-maheshwari-3...  Grad Student @UMD|MS in Data Science|Ex-SD Int...                                                                                                                                          False
4346  4a718c200c4a8f8d8542bcb5a887072b  PB.LIN_Connections_Exports.GP_Lin_Connections_...    2025-12-09T23:57:35.192Z     Sriram      Prasad                                   2025-12-09T23:57:35.192Z                                                  https://www.linkedin.com/in/sriramprasadkothap...  Robotics@Soterya| Robotics Grad | UMD | Automa...                                                                                                                                          False

[4347 rows x 19 columns]