In [4]:
import sqlite3
import numpy as np
import pandas as pd

In [7]:
db_path = "sqlite:///data.db"

In [5]:
df = pd.DataFrame(
    {
        "date": pd.date_range("2024-01-01", periods=10),
        "sales": np.random.randint(50, 500, 10),
        "region": np.random.choice(["North", "South", "East", "West"], 10),
    }
)

df

        date  sales region
0 2024-01-01    458  North
1 2024-01-02    167   East
2 2024-01-03    250  North
3 2024-01-04    213   West
4 2024-01-05    308  North
5 2024-01-06    353  South
6 2024-01-07    350  South
7 2024-01-08    366  North
8 2024-01-09    255   West
9 2024-01-10     58  South

In [12]:
df.to_sql(
    "my_table",
    db_path,
    # if_exists="replace",
    if_exists="append",
    index=False,
)

10

In [13]:
conn = sqlite3.connect("data.db")

df2 = pd.read_sql_query("SELECT * FROM my_table", conn)
print(df2)

conn.close()

                          date  sales region
0   2024-01-01 00:00:00.000000    458  North
1   2024-01-02 00:00:00.000000    167   East
2   2024-01-03 00:00:00.000000    250  North
3   2024-01-04 00:00:00.000000    213   West
4   2024-01-05 00:00:00.000000    308  North
5   2024-01-06 00:00:00.000000    353  South
6   2024-01-07 00:00:00.000000    350  South
7   2024-01-08 00:00:00.000000    366  North
8   2024-01-09 00:00:00.000000    255   West
9   2024-01-10 00:00:00.000000     58  South
10  2024-01-01 00:00:00.000000    458  North
11  2024-01-02 00:00:00.000000    167   East
12  2024-01-03 00:00:00.000000    250  North
13  2024-01-04 00:00:00.000000    213   West
14  2024-01-05 00:00:00.000000    308  North
15  2024-01-06 00:00:00.000000    353  South
16  2024-01-07 00:00:00.000000    350  South
17  2024-01-08 00:00:00.000000    366  North
18  2024-01-09 00:00:00.000000    255   West
19  2024-01-10 00:00:00.000000     58  South

In [17]:
query = """
SELECT *
FROM my_table
WHERE date >= '2024-01-01'
AND sales > 100
"""

df3 = pd.read_sql_query(query, db_path)
df3

                          date  sales region
0   2024-01-01 00:00:00.000000    458  North
1   2024-01-02 00:00:00.000000    167   East
2   2024-01-03 00:00:00.000000    250  North
3   2024-01-04 00:00:00.000000    213   West
4   2024-01-05 00:00:00.000000    308  North
5   2024-01-06 00:00:00.000000    353  South
6   2024-01-07 00:00:00.000000    350  South
7   2024-01-08 00:00:00.000000    366  North
8   2024-01-09 00:00:00.000000    255   West
9   2024-01-01 00:00:00.000000    458  North
10  2024-01-02 00:00:00.000000    167   East
11  2024-01-03 00:00:00.000000    250  North
12  2024-01-04 00:00:00.000000    213   West
13  2024-01-05 00:00:00.000000    308  North
14  2024-01-06 00:00:00.000000    353  South
15  2024-01-07 00:00:00.000000    350  South
16  2024-01-08 00:00:00.000000    366  North
17  2024-01-09 00:00:00.000000    255   West